 
 
                                        a     2
  119-1  ciŸu veë aravi­ a+ vari+ kuruëai
   63-2  cey vi­ai kaimmika eõõuti a+ vi­aikku
 
                                       a«tu     1
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
 
                                      akattu     1
   42-3  viñar akattu iyampum nàña em
 
                                       akam     1
  137-1  mel iyal arivai ni­ nal akam pulampa
 
                                       akal     2
   44-3  akal iru vicumpi­ mã­i­ um
  124-1  umaõar c›rntu ka©inta maruïki­ akal talai
 
                                    añaïki­ar     1
    6-2  i­itu añaïki­ar › màkkaë mu­ivu i­Ÿu
 
                                    añaikarai     1
  171-2  kañum pu­al añaikarai neñum kayattu iñña
 
                                   aõaïkiyàaïku     1
  119-2  kà­a yà­ai aõaïkiyàaïku
 
                                    aõaïkiyë     1
  119-4  vaëai uñai+ kaiyaë em aõaïkiyë ›
 
                                       ata­     1
  157-1  kukkå e­Ÿatu k©i ata­ etir
 
                                       atu     2
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
  371-4  maruv›­ t©i atu kàmam  peritu ›
 
                                       atta     1
  369-1  atta vàkai amalai vàl neŸŸu
 
                                      atta­     1
   93-3  a­­ai um atta­ um allar 
 
                                        am     4
   17-2  kuvi muki© erukku am kaõõi um cåñupa
   71-2  arumpiya cuõaïki­ am pakaññu iëa mulai
  124-2  år pà©tta­­a mai am perum kàñu
   63-3  am mà arivai um varum 
 
                                      amalai     1
  369-1  atta vàkai amalai vàl neŸŸu
 
                                    amaikuve­     1
  137-2  ni­+ tuŸantu amaikuve­ àyi­ e­+ tuŸantu
 
                                    amaitaŸku     1
    4-3  amaitaŸku amainta nam kàtalar
 
                                     amainta     1
    4-3  amaitaŸku amainta nam kàtalar
 
                                      amaivu     1
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
 
                                      ampi­     1
    1-2  cem^ kl ampi­ cem^ kññu yà­ai
 
                                       amma     1
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
 
                                      ayirai     1
  166-2  nàrai nirai peyarntu ayirai àrum
 
                                      aravi­     1
  119-1  ciŸu veë aravi­ a+ vari+ kuruëai
 
                                       ari     1
  369-2  ari àr cilampi­ arici àrppa+
 
                                      arici     1
  369-2  ari àr cilampi­ arici àrppa+
 
                                      aritu     1
  120-2  aritu v›ñña­ai àl ne¤cu › kàtali
 
                                      ariyaë     1
  120-4  ariyaë àkutal aŸiyàty ›
 
                                      arivai     2
   63-3  am mà arivai um varum 
  137-1  mel iyal arivai ni­ nal akam pulampa
 
                                       arum     2
   39-3  malai uñai arum curam e­pa nam
   68-3  arum pa­i aŸciram tãrkkum
 
                                     arumpiya     1
   71-2  arumpiya cuõaïki­ am pakaññu iëa mulai
 
                                      aruvi     3
   42-2  karuvi mà ma©ai vã©nte­a aruvi
  315-2  o©uku veë aruvi ïku malai nàña­
   96-1  aruvi v›ïkai+ peru malai nàñaŸku
 
                                     aruviyi­     1
  371-3  aruviyi­ viëaikkum nàña­oñu
 
                                       aruë     1
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
 
                                       alar     1
   97-4  maŸai alar àki ma­Ÿatta«tu ›
 
                                      allar     2
   93-3  a­­ai um atta­ um allar 
  102-4  cà­Ÿr allar yàm marãiyr ›
 
                                      allai     1
   47-4  nallai allai neñu veë nilavu ›
 
                                       avar     3
   37-4  a­pi­a t©i avar ce­Ÿa àŸu ›
   93-2  i­ uyir ka©iyi­um uraiyal avar namakku
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
 
                                      avintu     1
    6-1  naëëe­Ÿa­Ÿu* › yàmam col avintu
 
                                      avuõar     1
    1-1  cem^ kaëam paña+ ko­Ÿu avuõar+ t›ytta
 
                                      a©àal     1
  135-4  a©àal t©i a©uïkuvar celavu ›
 
                                    a©uïkuvar     1
  135-4  a©àal t©i a©uïkuvar celavu ›
 
                                     aëavi­Ÿu     1
    3-2  nãri­ um àr aëavi­Ÿu* › càral
 
                                    aëavaittu     1
  102-2  iruppi­ em aëavaittu a­Ÿu › varutti
 
                                       aŸal     1
  116-3  nuõ maõal aŸal vàrnta­­a
 
                                    aŸintàïku     1
  120-3  nallaë àkutal aŸintàïku
 
                                     aŸiyàty     1
  120-4  ariyaë àkutal aŸiyàty ›
 
                                     aŸciram     1
   68-3  arum pa­i aŸciram tãrkkum
 
                                       aŸŸu     1
  399-2  pàci aŸŸu › pacalai kàtalar
 
                                      a­aiya     1
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
 
                                     a­aiya­     1
  315-3  ¤àyiŸu a­aiya­ t©i
 
                                      a­pi­a     1
   37-4  a­pi­a t©i avar ce­Ÿa àŸu ›
 
                                       a­pu     2
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
 
                                       a­Ÿu     2
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
  102-2  iruppi­ em aëavaittu a­Ÿu › varutti
 
                                       a­­a     2
  122-1  paim kàl+ kokki­ pu­ puŸattu a­­a
   68-1  på©+ kàl a­­a cem kàl u©unti­
 
                                      a­­ày     1
   33-1  a­­ày iva­ r iëa màõàkka­
 
                                      a­­ai     1
   93-3  a­­ai um atta­ um allar 
 
                                       àka     2
   20-3  uravr uravr àka
   20-4  mañavam àka mañantai nàm ›
 
                                       àki     1
   97-4  maŸai alar àki ma­Ÿatta«tu ›
 
                                      àki­Ÿu     1
  166-4  oru ta­i vaiki­ pulampu àki­Ÿu ›
 
                                      àkuka     1
  137-4  pala àkuka yà­ celavuŸu takavu ›
 
                                      àkutal     3
  120-3  nallaë àkutal aŸintàïku
  120-4  ariyaë àkutal aŸiyàty ›
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
 
                                      àkupa     1
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
 
                                      àkuvai     1
   96-4  e­ àkuvai kol nal nutal nã ›
 
                                      àñavar     1
  135-2  ma­ai uŸai makaëirkku àñavar uyir e­a
 
                                    àñavarkku     1
  135-1  vi­ai › àñavarkku uyir › vàë nutal
 
                                      àmpal     1
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
 
                                       àyi­     5
   20-2  poruë vayi­+ pirivr uravr àyi­
   96-3  nakai e­a uõar›­ àyi­
  124-3  i­­à e­Ÿir àyi­
  384-3  nala­ uõñu tuŸatti àyi­
  137-2  ni­+ tuŸantu amaikuve­ àyi­ e­+ tuŸantu
 
                                      àyi­um     1
   42-1  kàmam o©ivatu àyi­um yàmattu+
 
                                        àr     3
    3-2  nãri­ um àr aëavi­Ÿu* › càral
  186-1  àr kali ›ŸŸoñu kàr talaimaõanta
  369-2  ari àr cilampi­ arici àrppa+
 
                                       àrum     1
  166-2  nàrai nirai peyarntu ayirai àrum
 
                                      àrkka     1
   17-3  maŸuki­ àrkka um pañupa
 
                                      àrkkum     1
   39-2  neŸŸu viëai u©i¤cil vaŸŸal àrkkum
 
                                      àrppa     1
  369-2  ari àr cilampi­ arici àrppa+
 
                                        àl     3
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
  120-2  aritu v›ñña­ai àl ne¤cu › kàtali
 
                                       àŸu     2
   37-4  a­pi­a t©i avar ce­Ÿa àŸu ›
   39-4  mulai iñai mu­inar ce­Ÿa àŸu ›
 
                                       à­à     1
   97-2  à­à nyoñu kà­ala«tu ›
 
                                        i     1
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
 
                                       iku     1
  109-2  puõari iku tirai taråum tuŸaiva­
 
                                       iñai     2
   47-2  irum puli+ kuruëaiyi­ t­Ÿum kàññu iñai
   39-4  mulai iñai mu­inar ce­Ÿa àŸu ›
 
                                       iñña     1
  171-2  kañum pu­al añaikarai neñum kayattu iñña
 
                                       ita©     1
  227-2  vàë mukam tumippa vaë ita© kuŸainta
 
                                       itu     1
  171-4  itu maŸŸu eva­  notumalar talai ›
 
                                       imai     1
    4-2  imai tãyppa­­a kaõõãr tàïki
 
                                     iyampum     1
   42-3  viñar akattu iyampum nàña em
 
                                       iyal     1
  137-1  mel iyal arivai ni­ nal akam pulampa
 
                                      irantu     1
   33-3  irantu åõ nirampà m›­iyoñu
 
                                     iravalar     1
  137-3  iravalar vàrà vaikal
 
                                       iru     1
   44-3  akal iru vicumpi­ mã­i­ um
 
                                      irunta     1
  109-3  puõariya irunta ¤à­Ÿu um
 
                                     iruppi­     1
  102-2  iruppi­ em aëavaittu a­Ÿu › varutti
 
                                       irum     1
   47-2  irum puli+ kuruëaiyi­ t­Ÿum kàññu iñai
 
                                        il     1
   63-1  ãtal um tuyttal um illrkku il e­a+
 
                                       ilam     1
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
 
                                       ilar     1
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
 
                                      illai     1
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
 
                                     illrkku     1
   63-1  ãtal um tuyttal um illrkku il e­a+
 
                                      ill­     1
  120-1  ill­ i­pam kàmuŸŸàaïku
 
                                       ivaõ     1
  227-3  kå©ai neytal um uñaittu ivaõ
 
                                       iva­     1
   33-1  a­­ày iva­ r iëa màõàkka­
 
                                     i©anta­a     1
   44-2  nkki nkki vàë i©anta­a ›
 
                                       i©ai     1
  188-3  vàl i©ai neki©ttr vàràr
 
                                     i©aikkum     1
    3-4  perum^ t›­ i©aikkum nàña­oñu nañpu ›
 
                                       iëa     2
   33-1  a­­ày iva­ r iëa màõàkka­
   71-2  arumpiya cuõaïki­ am pakaññu iëa mulai
 
                                     iëaiyaë     1
  119-3  iëaiyaë muëai vàë eyiŸŸaë
 
                                      iŸavi­     1
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
 
                                        i­     1
   93-2  i­ uyir ka©iyi­um uraiyal avar namakku
 
                                       i­am     1
   68-2  å©ppañu mutu kày u©ai i­am kavarum
 
                                       i­i     2
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
  171-1  kàõ i­i và©i t©i yàõar+
 
                                      i­itu     1
    6-2  i­itu añaïki­ar › màkkaë mu­ivu i­Ÿu
 
                                      i­iya     1
  124-4  i­iya  peruma tamiyrkku ma­ai ›
 
                                      i­pam     1
  120-1  ill­ i­pam kàmuŸŸàaïku
 
                                       i­Ÿu     1
    6-2  i­itu añaïki­ar › màkkaë mu­ivu i­Ÿu
 
                                      i­­atu     1
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
 
                                       i­­à     1
  124-3  i­­à e­Ÿir àyi­
 
                                     ãõñaiy›­     1
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
 
                                       ãtal     1
   63-1  ãtal um tuyttal um illrkku il e­a+
 
                                       uku     1
   47-1  karum kàl v›ïkai vã uku tuŸukal
 
                                       uñai     4
   39-3  malai uñai arum curam e­pa nam
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
  119-4  vaëai uñai+ kaiyaë em aõaïkiyë ›
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
 
                                     uñaittu     2
  227-3  kå©ai neytal um uñaittu ivaõ
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
 
                                     uñaiyar     1
   37-1  nacai peritu uñaiyar nalkal um nalkuvar
 
                                        uõ     2
  399-1  år uõ k›õi uõ tuŸai+ tokka
  399-1  år uõ k›õi uõ tuŸai+ tokka
 
                                      uõar›­     1
   96-3  nakai e­a uõar›­ àyi­
 
                                       uõñu     1
  384-3  nala­ uõñu tuŸatti àyi­
 
                                        um    24
   44-3  akal iru vicumpi­ mã­i­ um
  109-3  puõariya irunta ¤à­Ÿu um
  371-1  kai vaëai neki©tal um mey pacappu årtal um
   93-3  a­­ai um atta­ um allar 
   93-3  a­­ai um atta­ um allar 
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
    3-2  nãri­ um àr aëavi­Ÿu* › càral
   63-1  ãtal um tuyttal um illrkku il e­a+
  227-3  kå©ai neytal um uñaittu ivaõ
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
   17-1  mà e­a mañal um årpa på e­a+
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
   17-2  kuvi muki© erukku am kaõõi um cåñupa
    6-3  na­am^ talai ulakam um tu¤cum
   63-1  ãtal um tuyttal um illrkku il e­a+
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
   37-1  nacai peritu uñaiyar nalkal um nalkuvar
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
   17-3  maŸuki­ àrkka um pañupa
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
  371-1  kai vaëai neki©tal um mey pacappu årtal um
   63-3  am mà arivai um varum 
 
                                      umaõar     1
  124-1  umaõar c›rntu ka©inta maruïki­ akal talai
 
                                    uyarnta­Ÿu     1
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
 
                                       uyir     3
  135-2  ma­ai uŸai makaëirkku àñavar uyir e­a
  135-1  vi­ai › àñavarkku uyir › vàë nutal
   93-2  i­ uyir ka©iyi­um uraiyal avar namakku
 
                                      uytti     1
   63-4  emmai uytti  uraittici­ ne¤cu ›
 
                                      uravr     3
   20-3  uravr uravr àka
   20-2  poruë vayi­+ pirivr uravr àyi­
   20-3  uravr uravr àka
 
                                    uraittici­     1
   63-4  emmai uytti  uraittici­ ne¤cu ›
 
                                    uraittrum     1
  135-3  namakku uraittrum tàm ›
 
                                     uraiyal     1
   93-2  i­ uyir ka©iyi­um uraiyal avar namakku
 
                                     ulakattu     1
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
 
                                      ulakam     1
    6-3  na­am^ talai ulakam um tu¤cum
 
                                     u©i¤cil     1
   39-2  neŸŸu viëai u©i¤cil vaŸŸal àrkkum
 
                                     u©unti­     1
   68-1  på©+ kàl a­­a cem kàl u©unti­
 
                                      u©untu     1
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
 
                                       u©ai     1
   68-2  å©ppañu mutu kày u©ai i­am kavarum
 
                                      uëëam     1
  102-1  uëëi­ uëëam v›m › uëëàtu
 
                                      uëëàtu     1
  102-1  uëëi­ uëëam v›m › uëëàtu
 
                                      uëëi­     1
  102-1  uëëi­ uëëam v›m › uëëàtu
 
                                     uŸantai     1
  116-2  vaëam ke©u c©ar uŸantai+ perum tuŸai
 
                                       uŸai     1
  135-2  ma­ai uŸai makaëirkku àñavar uyir e­a
 
                                     uŸaivë     1
  116-1  yà­ nayantu uŸaivë t›m pày kåntal
 
                                        åõ     1
   33-3  irantu åõ nirampà m›­iyoñu
 
                                        år     4
  399-1  år uõ k›õi uõ tuŸai+ tokka
  166-3  år  na­Ÿu ma­ marantai
  124-2  år pà©tta­­a mai am perum kàñu
   33-2  ta­ år ma­Ÿattu e­­a­ kol 
 
                                       årà­     1
   97-3  tuŸaiva­ tam årà­ ›
 
                                       årum     1
   33-4  virunti­ årum perum cemmala­ ›
 
                                      årtal     1
  371-1  kai vaëai neki©tal um mey pacappu årtal um
 
                                       årpa     1
   17-1  mà e­a mañal um årpa på e­a+
 
                                     å©ppañu     1
   68-2  å©ppañu mutu kày u©ai i­am kavarum
 
                                      eõõuti     1
   63-2  cey vi­ai kaimmika eõõuti a+ vi­aikku
 
                                       etir     1
  157-1  kukkå e­Ÿatu k©i ata­ etir
 
                                        em     4
   42-3  viñar akattu iyampum nàña em
  119-4  vaëai uñai+ kaiyaë em aõaïkiyë ›
  102-2  iruppi­ em aëavaittu a­Ÿu › varutti
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
 
                                      emmai     1
   63-4  emmai uytti  uraittici­ ne¤cu ›
 
                                      eyiŸu     1
  186-3  eyiŸu e­a mukaiyum nàñaŸku+
 
                                     eyiŸŸaë     1
  119-3  iëaiyaë muëai vàë eyiŸŸaë
 
                                      erukku     1
   17-2  kuvi muki© erukku am kaõõi um cåñupa
 
                                       elli     1
   47-3  elli varunar kaëaviŸku
 
                                       eva­     3
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
  171-4  itu maŸŸu eva­  notumalar talai ›
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
 
                                     e©utaru     1
  315-1  e©utaru matiyam kañal+ kaõñàaïku
 
                                        e­     9
   96-4  e­ àkuvai kol nal nutal nã ›
  137-2  ni­+ tuŸantu amaikuve­ àyi­ e­+ tuŸantu
  157-2  tuñku e­Ÿa­Ÿu e­ tåu ne¤cam
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
 
                                       e­a     7
   17-1  mà e­a mañal um årpa på e­a+
   63-1  ãtal um tuyttal um illrkku il e­a+
  135-2  ma­ai uŸai makaëirkku àñavar uyir e­a
   96-3  nakai e­a uõar›­ àyi­
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
   17-1  mà e­a mañal um årpa på e­a+
  186-3  eyiŸu e­a mukaiyum nàñaŸku+
 
                                       e­i­     2
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
 
                                       e­pa     1
   39-3  malai uñai arum curam e­pa nam
 
                                      e­Ÿatu     1
  157-1  kukkå e­Ÿatu k©i ata­ etir
 
                                     e­Ÿa­Ÿu     1
  157-2  tuñku e­Ÿa­Ÿu e­ tåu ne¤cam
 
                                       e­Ÿi     1
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
 
                                      e­Ÿir     1
  124-3  i­­à e­Ÿir àyi­
 
                                      e­­a­     1
   33-2  ta­ år ma­Ÿattu e­­a­ kol 
 
                                        ›    69
    1-4  kuruti+ påvi­ kulai+ kàntaññu* ›
    3-4  perum^ t›­ i©aikkum nàña­oñu nañpu ›
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
    6-4  r yà­ ma­Ÿa tu¤càt›­ ›
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
   20-4  mañavam àka mañantai nàm ›
   33-4  virunti­ årum perum cemmala­ ›
   37-4  a­pi­a t©i avar ce­Ÿa àŸu ›
   39-4  mulai iñai mu­inar ce­Ÿa àŸu ›
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
   44-1  kàl › pari tappi­a › kaõ ›
   44-2  nkki nkki vàë i©anta­a ›
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
   47-4  nallai allai neñu veë nilavu ›
   63-4  emmai uytti  uraittici­ ne¤cu ›
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
   71-4  kal ke©u kà­avar nalkuŸu makaë ›
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
   96-4  e­ àkuvai kol nal nutal nã ›
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
   97-2  à­à nyoñu kà­ala«tu ›
   97-3  tuŸaiva­ tam årà­ ›
   97-4  maŸai alar àki ma­Ÿatta«tu ›
  102-4  cà­Ÿr allar yàm marãiyr ›
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
  116-4  nal neŸiyav+ › naŸum taõõiya ›
  119-4  vaëai uñai+ kaiyaë em aõaïkiyë ›
  120-4  ariyaë àkutal aŸiyàty ›
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
  124-4  i­iya  peruma tamiyrkku ma­ai ›
  135-3  namakku uraittrum tàm ›
  135-4  a©àal t©i a©uïkuvar celavu ›
  137-4  pala àkuka yà­ celavuŸu takavu ›
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
  166-4  oru ta­i vaiki­ pulampu àki­Ÿu ›
  171-4  itu maŸŸu eva­  notumalar talai ›
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
  227-4  t›r­ pkiya kà­alà­ ›
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
  369-4  celvàm t©i nalki­ar namar ›
  371-4  maruv›­ t©i atu kàmam  peritu ›
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
  399-4  viñuvu©i viñuvu©i+ parattalà­ ›
  135-1  vi­ai › àñavarkku uyir › vàë nutal
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
  102-1  uëëi­ uëëam v›m › uëëàtu
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
   44-1  kàl › pari tappi­a › kaõ ›
  120-2  aritu v›ñña­ai àl ne¤cu › kàtali
  102-3  và­ tyvaŸŸu › kàmam
    3-2  nãri­ um àr aëavi­Ÿu* › càral
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
  116-4  nal neŸiyav+ › naŸum taõõiya ›
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
  399-2  pàci aŸŸu › pacalai kàtalar
   44-1  kàl › pari tappi­a › kaõ ›
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
    6-2  i­itu añaïki­ar › màkkaë mu­ivu i­Ÿu
  188-1  mukai muŸŸi­a › mullai mullaiyoñu
    6-1  naëëe­Ÿa­Ÿu* › yàmam col avintu
  102-2  iruppi­ em aëavaittu a­Ÿu › varutti
  135-1  vi­ai › àñavarkku uyir › vàë nutal
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
 
                                      ›ŸŸoñu     1
  186-1  àr kali ›ŸŸoñu kàr talaimaõanta
 
                                     aiva­am     1
  371-2  mai pañu cilampi­ aiva­am vitti
 
                                       oru     2
  166-4  oru ta­i vaiki­ pulampu àki­Ÿu ›
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
 
                                     o©ivatu     1
   42-1  kàmam o©ivatu àyi­um yàmattu+
 
                                      o©uku     1
  315-2  o©uku veë aruvi ïku malai nàña­
 
                                            13
   33-2  ta­ år ma­Ÿattu e­­a­ kol 
   63-3  am mà arivai um varum 
   93-3  a­­ai um atta­ um allar 
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
   63-4  emmai uytti  uraittici­ ne¤cu ›
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
  166-3  år  na­Ÿu ma­ marantai
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
  171-4  itu maŸŸu eva­  notumalar talai ›
  371-4  maruv›­ t©i atu kàmam  peritu ›
  124-4  i­iya  peruma tamiyrkku ma­ai ›
  122-3  vanta­Ÿu và©i  màlai
 
                                       ïku     1
  315-2  o©uku veë aruvi ïku malai nàña­
 
                                       mai     1
  124-2  år pà©tta­­a mai am perum kàñu
 
                                        r     2
   33-1  a­­ày iva­ r iëa màõàkka­
    6-4  r yà­ ma­Ÿa tu¤càt›­ ›
 
                                      kaïkul     1
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
 
                                      kañal     2
  315-1  e©utaru matiyam kañal+ kaõñàaïku
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
 
                                       kañu     1
   39-1  vem tiŸal kañu vaëi poïkar+ pnte­a
 
                                      kañum     1
  171-2  kañum pu­al añaikarai neñum kayattu iñña
 
                                      kañai     1
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
 
                                       kaõ     2
   44-1  kàl › pari tappi­a › kaõ ›
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
 
                                    kaõñàaïku     1
  315-1  e©utaru matiyam kañal+ kaõñàaïku
 
                                      kaõõi     1
   17-2  kuvi muki© erukku am kaõõi um cåñupa
 
                                      kaõõãr     1
    4-2  imai tãyppa­­a kaõõãr tàïki
 
                                     kayattu     1
  171-2  kañum pu­al añaikarai neñum kayattu iñña
 
                                      karum     2
   47-1  karum kàl v›ïkai vã uku tuŸukal
    3-3  karum^ kl+ kuŸi¤ci+ på+ koõñu
 
                                     karumpu     1
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
 
                                      karuvi     1
   42-2  karuvi mà ma©ai vã©nte­a aruvi
 
                                       kal     1
   71-4  kal ke©u kà­avar nalkuŸu makaë ›
 
                                       kali     1
  186-1  àr kali ›ŸŸoñu kàr talaimaõanta
 
                                     kavarum     1
   68-2  å©ppañu mutu kày u©ai i­am kavarum
 
                                      kavi­     1
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
 
                                      ka©al     1
    1-3  ka©al toñi c›ey ku­Ÿam
 
                                     ka©inta     1
  124-1  umaõar c›rntu ka©inta maruïki­ akal talai
 
                                    ka©iyi­um     1
   93-2  i­ uyir ka©iyi­um uraiyal avar namakku
 
                                     ka©unti­     1
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
 
                                      kaëam     1
    1-1  cem^ kaëam paña+ ko­Ÿu avuõar+ t›ytta
 
                                    kaëaviŸku     1
   47-3  elli varunar kaëaviŸku
 
                                     kaëaiiya     1
   37-2  piñi paci kaëaiiya perum kai v›©am
 
                                       kàñu     1
  124-2  år pà©tta­­a mai am perum kàñu
 
                                      kàññu     1
   47-2  irum puli+ kuruëaiyi­ t­Ÿum kàññu iñai
 
                                       kàõ     1
  171-1  kàõ i­i và©i t©i yàõar+
 
                                     kàtalar     3
    4-3  amaitaŸku amainta nam kàtalar
  399-2  pàci aŸŸu › pacalai kàtalar
  157-3  të ty kàtalar+ pirikkum
 
                                      kàtali     1
  120-2  aritu v›ñña­ai àl ne¤cu › kàtali
 
                                     kàntaññu     1
    1-4  kuruti+ påvi­ kulai+ kàntaññu* ›
 
                                      kàmam     4
  102-3  và­ tyvaŸŸu › kàmam
   42-1  kàmam o©ivatu àyi­um yàmattu+
  371-4  maruv›­ t©i atu kàmam  peritu ›
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
 
                                   kàmuŸŸàaïku     1
  120-1  ill­ i­pam kàmuŸŸàaïku
 
                                       kày     1
   68-2  å©ppañu mutu kày u©ai i­am kavarum
 
                                       kàr     2
  186-1  àr kali ›ŸŸoñu kàr talaimaõanta
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
 
                                       kàl     6
   68-1  på©+ kàl a­­a cem kàl u©unti­
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
   68-1  på©+ kàl a­­a cem kàl u©unti­
   44-1  kàl › pari tappi­a › kaõ ›
  122-1  paim kàl+ kokki­ pu­ puŸattu a­­a
   47-1  karum kàl v›ïkai vã uku tuŸukal
 
                                       kà©     1
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
 
                                       kà­a     1
  119-2  kà­a yà­ai aõaïkiyàaïku
 
                                      kà­am     1
  369-3  kñai tåkkum kà­am
 
                                    kà­ala«tu     1
   97-2  à­à nyoñu kà­ala«tu ›
 
                                     kà­alà­     1
  227-4  t›r­ pkiya kà­alà­ ›
 
                                     kà­avar     1
   71-4  kal ke©u kà­avar nalkuŸu makaë ›
 
                                      kiëai     1
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
 
                                      kukkå     1
  157-1  kukkå e­Ÿatu k©i ata­ etir
 
                                      kuõñu     1
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
 
                                      kuruti     1
    1-4  kuruti+ påvi­ kulai+ kàntaññu* ›
 
                                     kuruëai     1
  119-1  ciŸu veë aravi­ a+ vari+ kuruëai
 
                                    kuruëaiyi­     1
   47-2  irum puli+ kuruëaiyi­ t­Ÿum kàññu iñai
 
                                      kulai     1
    1-4  kuruti+ påvi­ kulai+ kàntaññu* ›
 
                                       kuvi     1
   17-2  kuvi muki© erukku am kaõõi um cåñupa
 
                                     kuŸi¤ci     1
    3-3  karum^ kl+ kuŸi¤ci+ på+ koõñu
 
                                     kuŸittu     1
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
 
                                      kuŸum     1
  384-2  neñum pal kåntal kuŸum toñi makaëir
 
                                     kuŸainta     1
  227-2  vàë mukam tumippa vaë ita© kuŸainta
 
                                      ku­Ÿam     1
    1-3  ka©al toñi c›ey ku­Ÿam
 
                                      kåntal     2
  116-1  yà­ nayantu uŸaivë t›m pày kåntal
  384-2  neñum pal kåntal kuŸum toñi makaëir
 
                                     kåmpi­a     1
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
 
                                      kå©ai     1
  227-3  kå©ai neytal um uñaittu ivaõ
 
                                       ke©u     2
   71-4  kal ke©u kà­avar nalkuŸu makaë ›
  116-2  vaëam ke©u c©ar uŸantai+ perum tuŸai
 
                                       k›õi     1
  399-1  år uõ k›õi uõ tuŸai+ tokka
 
                                       kai     2
  371-1  kai vaëai neki©tal um mey pacappu årtal um
   37-2  piñi paci kaëaiiya perum kai v›©am
 
                                     kaimmika     1
   63-2  cey vi­ai kaimmika eõõuti a+ vi­aikku
 
                                      kaiyaë     1
  119-4  vaëai uñai+ kaiyaë em aõaïkiyë ›
 
                                      kokki­     1
  122-1  paim kàl+ kokki­ pu­ puŸattu a­­a
 
                                       koñi     1
  186-2  kollai+ pu­atta mullai mel koñi
 
                                      koõñu     1
    3-3  karum^ kl+ kuŸi¤ci+ på+ koõñu
 
                                       kol     2
   33-2  ta­ år ma­Ÿattu e­­a­ kol 
   96-4  e­ àkuvai kol nal nutal nã ›
 
                                      kollai     1
  186-2  kollai+ pu­atta mullai mel koñi
 
                                      koëi­     1
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
 
                                      ko­Ÿu     1
    1-1  cem^ kaëam paña+ ko­Ÿu avuõar+ t›ytta
 
                                      kñai     1
  369-3  kñai tåkkum kà­am
 
                                      kññu     1
    1-2  cem^ kl ampi­ cem^ kññu yà­ai
 
                                       kl     2
    1-2  cem^ kl ampi­ cem^ kññu yà­ai
    3-3  karum^ kl+ kuŸi¤ci+ på+ koõñu
 
                                       k©i     1
  157-1  kukkå e­Ÿatu k©i ata­ etir
 
                                       càay     1
   93-1  nal nalam tolaiya nalam mika+ càay
 
                                      càral     1
    3-2  nãri­ um àr aëavi­Ÿu* › càral
 
                                      cà­Ÿr     1
  102-4  cà­Ÿr allar yàm marãiyr ›
 
                                     cilampi­     2
  369-2  ari àr cilampi­ arici àrppa+
  371-2  mai pañu cilampi­ aiva­am vitti
 
                                       ciŸu     1
  119-1  ciŸu veë aravi­ a+ vari+ kuruëai
 
                                      ci­ai     1
   37-3  mel ci­ai yàam poëikkum
 
                                     cuõaïki­     1
   71-2  arumpiya cuõaïki­ am pakaññu iëa mulai
 
                                      curam     1
   39-3  malai uñai arum curam e­pa nam
 
                                      cåñupa     1
   17-2  kuvi muki© erukku am kaõõi um cåñupa
 
                                      cåññu     1
  227-1  påõ va­ainta­­a polam cåññu n›mi
 
                                       cåë     1
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
 
                                       cem     4
    1-1  cem^ kaëam paña+ ko­Ÿu avuõar+ t›ytta
   68-1  på©+ kàl a­­a cem kàl u©unti­
    1-2  cem^ kl ampi­ cem^ kññu yà­ai
    1-2  cem^ kl ampi­ cem^ kññu yà­ai
 
                                     cemmala­     1
   33-4  virunti­ årum perum cemmala­ ›
 
                                       cey     1
   63-2  cey vi­ai kaimmika eõõuti a+ vi­aikku
 
                                      ceyku     1
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
 
                                      celavu     1
  135-4  a©àal t©i a©uïkuvar celavu ›
 
                                     celavuŸu     1
  137-4  pala àkuka yà­ celavuŸu takavu ›
 
                                      celvàm     1
  369-4  celvàm t©i nalki­ar namar ›
 
                                      ce­Ÿa     2
   37-4  a­pi­a t©i avar ce­Ÿa àŸu ›
   39-4  mulai iñai mu­inar ce­Ÿa àŸu ›
 
                                       c›ey     1
    1-3  ka©al toñi c›ey ku­Ÿam
 
                                      c›rntu     1
  124-1  umaõar c›rntu ka©inta maruïki­ akal talai
 
                                       col     1
    6-1  naëëe­Ÿa­Ÿu* › yàmam col avintu
 
                                      c©ar     1
  116-2  vaëam ke©u c©ar uŸantai+ perum tuŸai
 
                                      ¤àyiŸu     1
  315-3  ¤àyiŸu a­aiya­ t©i
 
                                      ¤à­Ÿu     1
  109-3  puõariya irunta ¤à­Ÿu um
 
                                      takavu     1
  137-4  pala àkuka yà­ celavuŸu takavu ›
 
                                      takai     1
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
 
                                       taõ     2
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
 
                                     taõõiya     1
  116-4  nal neŸiyav+ › naŸum taõõiya ›
 
                                     tappi­a     1
   44-1  kàl › pari tappi­a › kaõ ›
 
                                       tam     1
   97-3  tuŸaiva­ tam årà­ ›
 
                                    tamiyrkku     1
  124-4  i­iya  peruma tamiyrkku ma­ai ›
 
                                      taråum     1
  109-2  puõari iku tirai taråum tuŸaiva­
 
                                      talai     3
  124-1  umaõar c›rntu ka©inta maruïki­ akal talai
    6-3  na­am^ talai ulakam um tu¤cum
  171-4  itu maŸŸu eva­  notumalar talai ›
 
                                   talaimaõanta     1
  186-1  àr kali ›ŸŸoñu kàr talaimaõanta
 
                                       ta­     1
   33-2  ta­ år ma­Ÿattu e­­a­ kol 
 
                                       ta­i     1
  166-4  oru ta­i vaiki­ pulampu àki­Ÿu ›
 
                                      tàïki     1
    4-2  imai tãyppa­­a kaõõãr tàïki
 
                                       tàm     1
  135-3  namakku uraittrum tàm ›
 
                                       tà­     1
  122-4  oru tà­ a­Ÿu › kaïkul um uñaittu ›
 
                                      tirai     2
  109-2  puõari iku tirai taråum tuŸaiva­
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
 
                                      tiŸal     1
   39-1  vem tiŸal kañu vaëi poïkar+ pnte­a
 
                                    tãyppa­­a     1
    4-2  imai tãyppa­­a kaõõãr tàïki
 
                                     tãrkkum     1
   68-3  arum pa­i aŸciram tãrkkum
 
                                     tu¤càt›­     1
    6-4  r yà­ ma­Ÿa tu¤càt›­ ›
 
                                      tu¤cum     1
    6-3  na­am^ talai ulakam um tu¤cum
 
                                      tuñku     1
  157-2  tuñku e­Ÿa­Ÿu e­ tåu ne¤cam
 
                                      tuõai     1
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
 
                                     tumippa     1
  227-2  vàë mukam tumippa vaë ita© kuŸainta
 
                                      tuyil     1
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
 
                                     tuyttal     1
   63-1  ãtal um tuyttal um illrkku il e­a+
 
                                     tuŸatti     1
  384-3  nala­ uõñu tuŸatti àyi­
 
                                    tuŸanta­a     1
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
 
                                     tuŸantu     3
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
  137-2  ni­+ tuŸantu amaikuve­ àyi­ e­+ tuŸantu
  137-2  ni­+ tuŸantu amaikuve­ àyi­ e­+ tuŸantu
 
                                     tuŸukal     1
   47-1  karum kàl v›ïkai vã uku tuŸukal
 
                                      tuŸai     2
  116-2  vaëam ke©u c©ar uŸantai+ perum tuŸai
  399-1  år uõ k›õi uõ tuŸai+ tokka
 
                                     tuŸaiva­     2
  109-2  puõari iku tirai taråum tuŸaiva­
   97-3  tuŸaiva­ tam årà­ ›
 
                                       tåu     1
  157-2  tuñku e­Ÿa­Ÿu e­ tåu ne¤cam
 
                                      tåkkum     1
  369-3  kñai tåkkum kà­am
 
                                       t›m     1
  116-1  yà­ nayantu uŸaivë t›m pày kåntal
 
                                      t›yum     1
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
 
                                      t›ytta     1
    1-1  cem^ kaëam paña+ ko­Ÿu avuõar+ t›ytta
 
                                      t›r­     1
  227-4  t›r­ pkiya kà­alà­ ›
 
                                       t›­     1
    3-4  perum^ t›­ i©aikkum nàña­oñu nañpu ›
 
                                      tokka     1
  399-1  år uõ k›õi uõ tuŸai+ tokka
 
                                     toñarpu     1
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
 
                                       toñi     2
    1-3  ka©al toñi c›ey ku­Ÿam
  384-2  neñum pal kåntal kuŸum toñi makaëir
 
                                     toñuvu©i     2
  399-3  toñuvu©i+ toñuvu©i nãïki
  399-3  toñuvu©i+ toñuvu©i nãïki
 
                                     tolaiya     1
   93-1  nal nalam tolaiya nalam mika+ càay
 
                                       ty     1
  157-3  të ty kàtalar+ pirikkum
 
                                     tyvaŸŸu     1
  102-3  và­ tyvaŸŸu › kàmam
 
                                       t©i     7
  315-3  ¤àyiŸu a­aiya­ t©i
  371-4  maruv›­ t©i atu kàmam  peritu ›
   37-4  a­pi­a t©i avar ce­Ÿa àŸu ›
  135-4  a©àal t©i a©uïkuvar celavu ›
  186-4  tuyil tuŸanta­a àl t©i em kaõ ›
  369-4  celvàm t©i nalki­ar namar ›
  171-1  kàõ i­i và©i t©i yàõar+
 
                                       të     4
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
  157-3  të ty kàtalar+ pirikkum
   71-3  perum të nuõukiya nucuppi­
 
                                      t­Ÿum     1
   47-2  irum puli+ kuruëaiyi­ t­Ÿum kàññu iñai
 
                                      nakai     1
   96-3  nakai e­a uõar›­ àyi­
 
                                      nacai     1
   37-1  nacai peritu uñaiyar nalkal um nalkuvar
 
                                      nañpu     1
    3-4  perum^ t›­ i©aikkum nàña­oñu nañpu ›
 
                                       nam     2
   39-3  malai uñai arum curam e­pa nam
    4-3  amaitaŸku amainta nam kàtalar
 
                                     namakku     2
   93-2  i­ uyir ka©iyi­um uraiyal avar namakku
  135-3  namakku uraittrum tàm ›
 
                                      namar     1
  369-4  celvàm t©i nalki­ar namar ›
 
                                     nayantu     1
  116-1  yà­ nayantu uŸaivë t›m pày kåntal
 
                                       nal     5
  137-1  mel iyal arivai ni­ nal akam pulampa
   93-1  nal nalam tolaiya nalam mika+ càay
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
   96-4  e­ àkuvai kol nal nutal nã ›
  116-4  nal neŸiyav+ › naŸum taõõiya ›
 
                                      nalam     3
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
   93-1  nal nalam tolaiya nalam mika+ càay
   93-1  nal nalam tolaiya nalam mika+ càay
 
                                      nala­     2
  384-3  nala­ uõñu tuŸatti àyi­
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
 
                                      nalkal     1
   37-1  nacai peritu uñaiyar nalkal um nalkuvar
 
                                     nalki­ar     1
  369-4  celvàm t©i nalki­ar namar ›
 
                                     nalkuvar     1
   37-1  nacai peritu uñaiyar nalkal um nalkuvar
 
                                     nalkuŸu     1
   71-4  kal ke©u kà­avar nalkuŸu makaë ›
 
                                      nallaë     1
  120-3  nallaë àkutal aŸintàïku
 
                                      nallai     1
   47-4  nallai allai neñu veë nilavu ›
 
                                   naëëe­Ÿa­Ÿu     1
    6-1  naëëe­Ÿa­Ÿu* › yàmam col avintu
 
                                      naŸum     1
  116-4  nal neŸiyav+ › naŸum taõõiya ›
 
                                      na­am     1
    6-3  na­am^ talai ulakam um tu¤cum
 
                                      na­Ÿu     2
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
  166-3  år  na­Ÿu ma­ marantai
 
                                       nàña     1
   42-3  viñar akattu iyampum nàña em
 
                                     nàñaŸku     2
   96-1  aruvi v›ïkai+ peru malai nàñaŸku
  186-3  eyiŸu e­a mukaiyum nàñaŸku+
 
                                      nàña­     1
  315-2  o©uku veë aruvi ïku malai nàña­
 
                                     nàña­oñu     2
  371-3  aruviyi­ viëaikkum nàña­oñu
    3-4  perum^ t›­ i©aikkum nàña­oñu nañpu ›
 
                                       nàm     1
   20-4  mañavam àka mañantai nàm ›
 
                                      nàrai     1
  166-2  nàrai nirai peyarntu ayirai àrum
 
                                     nirampà     1
   33-3  irantu åõ nirampà m›­iyoñu
 
                                      nirai     1
  166-2  nàrai nirai peyarntu ayirai àrum
 
                                     nilatti­     1
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
 
                                      nilavu     1
   47-4  nallai allai neñu veë nilavu ›
 
                                       ni­     4
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
  137-2  ni­+ tuŸantu amaikuve­ àyi­ e­+ tuŸantu
  137-1  mel iyal arivai ni­ nal akam pulampa
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
 
                                        nã     1
   96-4  e­ àkuvai kol nal nutal nã ›
 
                                      nãkki     1
   20-1  aruë um a­pu um nãkki tuõai tuŸantu
 
                                      nãïki     1
  399-3  toñuvu©i+ toñuvu©i nãïki
 
                                       nãr     1
  122-2  kuõñu nãr àmpal um kåmpi­a i­i ›
 
                                      nãri­     1
    3-2  nãri­ um àr aëavi­Ÿu* › càral
 
                                     nucuppi­     1
   71-3  perum të nuõukiya nucuppi­
 
                                       nuõ     1
  116-3  nuõ maõal aŸal vàrnta­­a
 
                                     nuõukiya     1
   71-3  perum të nuõukiya nucuppi­
 
                                      nutal     3
  135-1  vi­ai › àñavarkku uyir › vàë nutal
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
   96-4  e­ àkuvai kol nal nutal nã ›
 
                                     neki©tal     1
  371-1  kai vaëai neki©tal um mey pacappu årtal um
 
                                    neki©ttr     1
  188-3  vàl i©ai neki©ttr vàràr
 
                                      ne¤cam     1
  157-2  tuñku e­Ÿa­Ÿu e­ tåu ne¤cam
 
                                      ne¤cu     5
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
   63-4  emmai uytti  uraittici­ ne¤cu ›
  120-2  aritu v›ñña­ai àl ne¤cu › kàtali
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
 
                                       neñu     1
   47-4  nallai allai neñu veë nilavu ›
 
                                      neñum     2
  171-2  kañum pu­al añaikarai neñum kayattu iñña
  384-2  neñum pal kåntal kuŸum toñi makaëir
 
                                      neytal     1
  227-3  kå©ai neytal um uñaittu ivaõ
 
                                     neru¤ci     1
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
 
                                     neŸiyav     1
  116-4  nal neŸiyav+ › naŸum taõõiya ›
 
                                      neŸŸu     2
  369-1  atta vàkai amalai vàl neŸŸu
   39-2  neŸŸu viëai u©i¤cil vaŸŸal àrkkum
 
                                       n›mi     1
  227-1  påõ va­ainta­­a polam cåññu n›mi
 
                                    notumalar     1
  171-4  itu maŸŸu eva­  notumalar talai ›
 
                                      nkki     2
   44-2  nkki nkki vàë i©anta­a ›
   44-2  nkki nkki vàë i©anta­a ›
 
                                       nm     3
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
    4-4  amaivu ilar àkutal nm e­ ne¤cu ›
    4-1  nm e­ ne¤cu* › nm e­ ne¤cu* ›
 
                                      nyoñu     1
   97-2  à­à nyoñu kà­ala«tu ›
 
                                     pakaññu     1
   71-2  arumpiya cuõaïki­ am pakaññu iëa mulai
 
                                     pacappu     1
  371-1  kai vaëai neki©tal um mey pacappu årtal um
 
                                     pacalai     1
  399-2  pàci aŸŸu › pacalai kàtalar
 
                                       paci     1
   37-2  piñi paci kaëaiiya perum kai v›©am
 
                                       paña     1
    1-1  cem^ kaëam paña+ ko­Ÿu avuõar+ t›ytta
 
                                       pañu     2
  371-2  mai pañu cilampi­ aiva­am vitti
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
 
                                      pañupa     1
   17-3  maŸuki­ àrkka um pañupa
 
                                    paññàaïku     1
  171-3  mã­ valai mà+ paññàaïku
 
                                      paõai     2
  384-1  u©untu uñai+ ka©unti­ karumpu uñai+ paõai+ të
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
 
                                    parattalà­     1
  399-4  viñuvu©i viñuvu©i+ parattalà­ ›
 
                                       pari     1
   44-1  kàl › pari tappi­a › kaõ ›
 
                                       pal     1
  384-2  neñum pal kåntal kuŸum toñi makaëir
 
                                       pala     1
  137-4  pala àkuka yà­ celavuŸu takavu ›
 
                                      palar     1
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
 
                                      paŸai     1
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
 
                                       pa­i     1
   68-3  arum pa­i aŸciram tãrkkum
 
                                       pàci     1
  399-2  pàci aŸŸu › pacalai kàtalar
 
                                       pày     1
  116-1  yà­ nayantu uŸaivë t›m pày kåntal
 
                                    pà©tta­­a     1
  124-2  år pà©tta­­a mai am perum kàñu
 
                                       piñi     1
   37-2  piñi paci kaëaiiya perum kai v›©am
 
                                     pirikkum     1
  157-3  të ty kàtalar+ pirikkum
 
                                     pirivr     1
   20-2  poruë vayi­+ pirivr uravr àyi­
 
                                      piŸar     1
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
 
                                      piŸitu     2
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
   17-4  piŸitu um àkupa kàmam kà©+ koëi­ ›
 
                                      puõari     1
  109-2  puõari iku tirai taråum tuŸaiva­
 
                                     puõariya     1
  109-3  puõariya irunta ¤à­Ÿu um
 
                                     pulampa     1
  137-1  mel iyal arivai ni­ nal akam pulampa
 
                                     pulampu     1
  166-4  oru ta­i vaiki­ pulampu àki­Ÿu ›
 
                                      pulavi     1
   93-4  pulavi a«tu eva­  a­pu ilam kañai ›
 
                                       puli     1
   47-2  irum puli+ kuruëaiyi­ t­Ÿum kàññu iñai
 
                                       puŸa     1
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
 
                                     puŸattu     1
  122-1  paim kàl+ kokki­ pu­ puŸattu a­­a
 
                                       pu­     1
  122-1  paim kàl+ kokki­ pu­ puŸattu a­­a
 
                                     pu­atta     1
  186-2  kollai+ pu­atta mullai mel koñi
 
                                      pu­am     1
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
 
                                      pu­al     1
  171-2  kañum pu­al añaikarai neñum kayattu iñña
 
                                        på     2
   17-1  mà e­a mañal um årpa på e­a+
    3-3  karum^ kl+ kuŸi¤ci+ på+ koõñu
 
                                       påõ     1
  227-1  påõ va­ainta­­a polam cåññu n›mi
 
                                      påvi­     1
    1-4  kuruti+ påvi­ kulai+ kàntaññu* ›
 
                                       på©     1
   68-1  på©+ kàl a­­a cem kàl u©unti­
 
                                   peyarttali­     1
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
 
                                     peyarntu     1
  166-2  nàrai nirai peyarntu ayirai àrum
 
                                      peritu     3
   37-1  nacai peritu uñaiyar nalkal um nalkuvar
  371-4  maruv›­ t©i atu kàmam  peritu ›
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
 
                                       peru     1
   96-1  aruvi v›ïkai+ peru malai nàñaŸku
 
                                      perum     8
  124-2  år pà©tta­­a mai am perum kàñu
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
   37-2  piñi paci kaëaiiya perum kai v›©am
   33-4  virunti­ årum perum cemmala­ ›
  116-2  vaëam ke©u c©ar uŸantai+ perum tuŸai
    3-4  perum^ t›­ i©aikkum nàña­oñu nañpu ›
   71-3  perum të nuõukiya nucuppi­
  315-4  neru¤ci a­aiya e­ perum paõai+ të ›
 
                                      peruma     1
  124-4  i­iya  peruma tamiyrkku ma­ai ›
 
                                       paim     1
  122-1  paim kàl+ kokki­ pu­ puŸattu a­­a
 
                                      poïkar     1
   39-1  vem tiŸal kañu vaëi poïkar+ pnte­a
 
                                      poruë     1
   20-2  poruë vayi­+ pirivr uravr àyi­
 
                                      polam     1
  227-1  påõ va­ainta­­a polam cåññu n›mi
 
                                     poëikkum     1
   37-3  mel ci­ai yàam poëikkum
 
                                      pkiya     1
  227-4  t›r­ pkiya kà­alà­ ›
 
                                     pnte­a     1
   39-1  vem tiŸal kañu vaëi poïkar+ pnte­a
 
                                       pl     1
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
 
                                      makaë     1
   71-4  kal ke©u kà­avar nalkuŸu makaë ›
 
                                     makaëir     1
  384-2  neñum pal kåntal kuŸum toñi makaëir
 
                                    makaëirkku     1
  135-2  ma­ai uŸai makaëirkku àñavar uyir e­a
 
                                     maki©na     1
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
 
                                     mañantai     1
   20-4  mañavam àka mañantai nàm ›
 
                                      mañal     1
   17-1  mà e­a mañal um årpa på e­a+
 
                                     mañavam     1
   20-4  mañavam àka mañantai nàm ›
 
                                     maõanta     1
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
 
                                      maõal     1
  116-3  nuõ maõal aŸal vàrnta­­a
 
                                     matiyam     1
  315-1  e©utaru matiyam kañal+ kaõñàaïku
 
                                     marantai     1
  166-3  år  na­Ÿu ma­ marantai
 
                                     marãiyr     1
  102-4  cà­Ÿr allar yàm marãiyr ›
 
                                     maruïki­     1
  124-1  umaõar c›rntu ka©inta maruïki­ akal talai
 
                                     maruntu     3
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
 
                                     maruv›­     1
  371-4  maruv›­ t©i atu kàmam  peritu ›
 
                                      malai     3
   39-3  malai uñai arum curam e­pa nam
   96-1  aruvi v›ïkai+ peru malai nàñaŸku
  315-2  o©uku veë aruvi ïku malai nàña­
 
                                      ma©ai     1
   42-2  karuvi mà ma©ai vã©nte­a aruvi
 
                                     maŸuki­     1
   17-3  maŸuki­ àrkka um pañupa
 
                                      maŸai     1
   97-4  maŸai alar àki ma­Ÿatta«tu ›
 
                                      maŸŸu     1
  171-4  itu maŸŸu eva­  notumalar talai ›
 
                                       ma­     2
  109-4  i­­atu ma­  nal nutal+ kavi­ ›
  166-3  år  na­Ÿu ma­ marantai
 
                                      ma­ai     2
  135-2  ma­ai uŸai makaëirkku àñavar uyir e­a
  124-4  i­iya  peruma tamiyrkku ma­ai ›
 
                                      ma­Ÿa     2
   44-4  palar › ma­Ÿa i ulakattu+ piŸar ›
    6-4  r yà­ ma­Ÿa tu¤càt›­ ›
 
                                   ma­Ÿatta«tu     1
   97-4  maŸai alar àki ma­Ÿatta«tu ›
 
                                     ma­Ÿattu     1
   33-2  ta­ år ma­Ÿattu e­­a­ kol 
 
                                        mà     4
   63-3  am mà arivai um varum 
   17-1  mà e­a mañal um årpa på e­a+
  171-3  mã­ valai mà+ paññàaïku
   42-2  karuvi mà ma©ai vã©nte­a aruvi
 
                                      màkkaë     1
    6-2  i­itu añaïki­ar › màkkaë mu­ivu i­Ÿu
 
                                       màõ     1
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
 
                                     màõàkka­     1
   33-1  a­­ày iva­ r iëa màõàkka­
 
                                      màrpu     1
   68-4  maruntu piŸitu illai avar maõanta màrpu ›
 
                                      màlai     2
  122-3  vanta­Ÿu và©i  màlai
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
 
                                       mika     2
   93-1  nal nalam tolaiya nalam mika+ càay
  384-4  mika na­Ÿu amma maki©na ni­ cåë ›
 
                                       mã­     1
  171-3  mã­ valai mà+ paññàaïku
 
                                      mã­i­     1
   44-3  akal iru vicumpi­ mã­i­ um
 
                                      mukam     1
  227-2  vàë mukam tumippa vaë ita© kuŸainta
 
                                      muki©     1
   17-2  kuvi muki© erukku am kaõõi um cåñupa
 
                                      mukai     1
  188-1  mukai muŸŸi­a › mullai mullaiyoñu
 
                                     mukaiyum     1
  186-3  eyiŸu e­a mukaiyum nàñaŸku+
 
                                     muñaïku     1
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
 
                                       mutu     1
   68-2  å©ppañu mutu kày u©ai i­am kavarum
 
                                      mulai     2
   71-2  arumpiya cuõaïki­ am pakaññu iëa mulai
   39-4  mulai iñai mu­inar ce­Ÿa àŸu ›
 
                                      mullai     2
  188-1  mukai muŸŸi­a › mullai mullaiyoñu
  186-2  kollai+ pu­atta mullai mel koñi
 
                                    mullaiyoñu     1
  188-1  mukai muŸŸi­a › mullai mullaiyoñu
 
                                       muë     1
  109-1  muë+ kàl iŸavi­ muñaïku puŸa+ perum kiëai
 
                                      muëai     1
  119-3  iëaiyaë muëai vàë eyiŸŸaë
 
                                     muŸŸi­a     2
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
  188-1  mukai muŸŸi­a › mullai mullaiyoñu
 
                                     mu­inar     1
   39-4  mulai iñai mu­inar ce­Ÿa àŸu ›
 
                                      mu­ivu     1
    6-2  i­itu añaïki­ar › màkkaë mu­ivu i­Ÿu
 
                                       mey     1
  371-1  kai vaëai neki©tal um mey pacappu årtal um
 
                                       mel     3
  137-1  mel iyal arivai ni­ nal akam pulampa
  186-2  kollai+ pu­atta mullai mel koñi
   37-3  mel ci­ai yàam poëikkum
 
                                     m›­iyoñu     1
   33-3  irantu åõ nirampà m›­iyoñu
 
                                       mai     1
  371-2  mai pañu cilampi­ aiva­am vitti
 
                                       yàam     1
   37-3  mel ci­ai yàam poëikkum
 
                                      yàõar     1
  171-1  kàõ i­i và©i t©i yàõar+
 
                                       yàm     1
  102-4  cà­Ÿr allar yàm marãiyr ›
 
                                     yàmattu     1
   42-1  kàmam o©ivatu àyi­um yàmattu+
 
                                      yàmam     1
    6-1  naëëe­Ÿa­Ÿu* › yàmam col avintu
 
                                       yà­     6
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
   96-2  yà­ eva­ ceyku  e­Ÿi yà­ atu
   97-1  yà­ › ãõñaiy›­ › e­ nala­ ›
  137-4  pala àkuka yà­ celavuŸu takavu ›
  116-1  yà­ nayantu uŸaivë t›m pày kåntal
    6-4  r yà­ ma­Ÿa tu¤càt›­ ›
 
                                      yà­ai     2
    1-2  cem^ kl ampi­ cem^ kññu yà­ai
  119-2  kà­a yà­ai aõaïkiyàaïku
 
                                     vanta­Ÿu     3
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
  188-4  màlai vanta­Ÿu e­ màõ nalam kuŸittu ›
  122-3  vanta­Ÿu và©i  màlai
 
                                      vayi­     1
   20-2  poruë vayi­+ pirivr uravr àyi­
 
                                     vayi­à­     1
   42-4  toñarpu um t›yum  ni­ vayi­à­ ›
 
                                       vari     1
  119-1  ciŸu veë aravi­ a+ vari+ kuruëai
 
                                     varutti     1
  102-2  iruppi­ em aëavaittu a­Ÿu › varutti
 
                                     varunar     1
   47-3  elli varunar kaëaviŸku
 
                                      varum     1
   63-3  am mà arivai um varum 
 
                                      valai     1
  171-3  mã­ valai mà+ paññàaïku
 
                                       vaë     1
  227-2  vàë mukam tumippa vaë ita© kuŸainta
 
                                      vaëam     1
  116-2  vaëam ke©u c©ar uŸantai+ perum tuŸai
 
                                       vaëi     1
   39-1  vem tiŸal kañu vaëi poïkar+ pnte­a
 
                                      vaëai     2
  119-4  vaëai uñai+ kaiyaë em aõaïkiyë ›
  371-1  kai vaëai neki©tal um mey pacappu årtal um
 
                                      vaŸŸal     1
   39-2  neŸŸu viëai u©i¤cil vaŸŸal àrkkum
 
                                   va­ainta­­a     1
  227-1  påõ va­ainta­­a polam cåññu n›mi
 
                                      vàkai     1
  369-1  atta vàkai amalai vàl neŸŸu
 
                                       vàrà     1
  137-3  iravalar vàrà vaikal
 
                                      vàràr     1
  188-3  vàl i©ai neki©ttr vàràr
 
                                    vàrnta­­a     1
  116-3  nuõ maõal aŸal vàrnta­­a
 
                                       vàl     2
  188-3  vàl i©ai neki©ttr vàràr
  369-1  atta vàkai amalai vàl neŸŸu
 
                                       và©i     2
  122-3  vanta­Ÿu và©i  màlai
  171-1  kàõ i­i và©i t©i yàõar+
 
                                       vàë     5
   44-2  nkki nkki vàë i©anta­a ›
  119-3  iëaiyaë muëai vàë eyiŸŸaë
  135-1  vi­ai › àñavarkku uyir › vàë nutal
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
  227-2  vàë mukam tumippa vaë ita© kuŸainta
 
                                       và­     1
  102-3  và­ tyvaŸŸu › kàmam
 
                                      và­i­     1
    3-1  nilatti­ um peritu › và­i­ um uyarnta­Ÿu
 
                                     vicumpi­     1
   44-3  akal iru vicumpi­ mã­i­ um
 
                                      viñar     1
   42-3  viñar akattu iyampum nàña em
 
                                     viñuvu©i     2
  399-4  viñuvu©i viñuvu©i+ parattalà­ ›
  399-4  viñuvu©i viñuvu©i+ parattalà­ ›
 
                                      vitti     1
  371-2  mai pañu cilampi­ aiva­am vitti
 
                                      viya­     1
  188-2  takai muŸŸi­a › taõ kàr viya­ pu­am
 
                                     virunti­     1
   33-4  virunti­ årum perum cemmala­ ›
 
                                      viëai     1
   39-2  neŸŸu viëai u©i¤cil vaŸŸal àrkkum
 
                                    viëaikkum     1
  371-3  aruviyi­ viëaikkum nàña­oñu
 
                                      vi­ai     2
  135-1  vi­ai › àñavarkku uyir › vàë nutal
   63-2  cey vi­ai kaimmika eõõuti a+ vi­aikku
 
                                     vi­aikku     1
   63-2  cey vi­ai kaimmika eõõuti a+ vi­aikku
 
                                        vã     1
   47-1  karum kàl v›ïkai vã uku tuŸukal
 
                                     vã©nte­a     1
   42-2  karuvi mà ma©ai vã©nte­a aruvi
 
                                       vem     1
   39-1  vem tiŸal kañu vaëi poïkar+ pnte­a
 
                                       veë     4
  119-1  ciŸu veë aravi­ a+ vari+ kuruëai
  315-2  o©uku veë aruvi ïku malai nàña­
   47-4  nallai allai neñu veë nilavu ›
  166-1  taõ kañal+ pañu tirai peyarttali­ veë paŸai
 
                                      v›ïkai     2
   96-1  aruvi v›ïkai+ peru malai nàñaŸku
   47-1  karum kàl v›ïkai vã uku tuŸukal
 
                                     v›ñña­ai     1
  120-2  aritu v›ñña­ai àl ne¤cu › kàtali
 
                                       v›m     1
  102-1  uëëi­ uëëam v›m › uëëàtu
 
                                      v›©am     1
   37-2  piñi paci kaëaiiya perum kai v›©am
 
                                      vaikal     1
  137-3  iravalar vàrà vaikal
 
                                     vaikaŸai     1
  157-4  vàë pl vaikaŸai vanta­Ÿu àl e­a ›
 
                                      vaiki­     1
  166-4  oru ta­i vaiki­ pulampu àki­Ÿu ›
 
                                      vaippu     2
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
   71-1  maruntu e­i­ maruntu › vaippu e­i­ vaippu ›
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
1
 TOTAL WORDS READ      =      829
 TOTAL WORDS SELECTED  =      829
 TOTAL WORDS PICKED    =      829
 TOTAL WORDS SAMPLED   =      829
 TOTAL WORDS KEPT      =      829
 TOTAL VOCABULARY      =      540
