R 79,T 5,police Pc7pdy
 
 
Page 1                                      a     4
 29  a+ nàl iñattu* um meynnàõ orãi
 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 44  a+ poruë+ pañuppi­um varainilai i­Ÿu* ›
  7  a+ må­Ÿu* e­pa t©ikku* uõarcci
 
                                     akam     1
 32  tiïkaë iraõñi­ akam e­a mo©ipa
 
                                     aka­     1
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
 
                                    aka­Ÿu     1
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 
                                     acca     1
 30  àŸupàrttu* uŸŸa acca+ kiëavi ~um
 
                                    accam     1
 31  àŸu* i­­àmai ~um åŸu* um accam um
 
                                    a¤cum     1
 29  ava­ åŸu* a¤cum^ kàlam àyi­um
 
                                     atu     1
  2  atu ~›
 
                                   antaõar     1
  1  antaõar aru-maŸai ma­Ÿal eññi­uë
 
                                    ampal     1
 22  ampal um alar um^ kaëavu
 
                                    aracar     1
 38  aracar allà ›­aiyrkku* um
 
                                    arukal     1
 11  mu­­uŸu puõarcciyi­ arukal um uõñu* ›
 
                                    arukum     1
 11  ta­= uë+ kuŸippi­ai arukum^ t©ikku
 
                                  aru-maŸai     1
  1  antaõar aru-maŸai ma­Ÿal eññi­uë
 
                                     alar     1
 22  ampal um alar um^ kaëavu
 
                                     alla     3
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 59  kiëanta alla v›Ÿu piŸa t­Ÿi­um
 
                                    allatu     5
 21  iravu ma­ai ikanta kuŸiyiñattu* allatu
  8  àïku* uõarntu* allatu ki©avë t›ettu+
Page 2  9  pi­­ar allatu kiëavi t­Ÿàtu
  4  av= iyalpu* allatu kåñña+ kåñal
 28  mu­­am allatu kåŸŸu* avaõ illai
 
                                     allà     1
 38  aracar allà ›­aiyrkku* um
 
                                      av     1
  4  av= iyalpu* allatu kåñña+ kåñal
 
                                     avaõ     2
 28  mu­­am allatu kåŸŸu* avaõ illai
 29  varaivu* etirkoëëàtu tamar avaõ maŸuppi­um
 
                                    avaruë     1
 27  avaruë
 
                                     avaë     1
  2  tà­ › avaë › tamiyar kàõa+
 
                                   avaŸŸuë     2
 36  avaŸŸuë
 57  avaŸŸuë
 
                                     ava­     7
 29  ava­ åŸu* a¤cum^ kàlam àyi­um
  9  mu­­uŸa uõari­um ava­ kuŸai-uŸŸa
 55  ava­+ puõarvu* aŸiyum kuŸippi­ à­a
 49  ava­ vayi­ kiëappi­ varaivi­ poruññu* ›
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
  7  iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
 
                                   ava­oñu     1
 12  màya+ puõarcci ava­oñu nakàa
 
                                   avvayi­     3
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 35  àïka àŸu* › avvayi­+ pirivu* ›
 
                                    a©ital     1
 31  ta­­ai a©ital um ki©avŸku* illai
 
                                    a©inta     1
 30  ta­­ai a©inta kiëavi ellàm
 
                                    aŸattu     1
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 
                                   aŸattoñu     1
 29  aŸattoñu niŸŸal t©ikku* um urittu* ›
 
                                    aŸintu     1
 59  eccam àki varum va©i aŸintu
 
                                    aŸipa     1
Page 3 27  tày aŸivuŸutali­ ›­r um aŸipa
 
                                    aŸiya     3
 52  o©intr aŸiya ~um aŸiyàmai ~um
 18  aŸiya+ kiëanta iñam e­a mo©ipa
 26  a­­avar aŸiya+ paõpu* àkum= ›
 
                                   aŸiyàmai     1
 52  o©intr aŸiya ~um aŸiyàmai ~um
 
                                    aŸiyàë     1
 12  aŸiyàë pŸal um kuŸiyàë kåŸal um
 
                                    aŸiyum     3
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 55  ava­+ puõarvu* aŸiyum kuŸippi­ à­a
 
                                 aŸivuŸutali­     1
 27  tày aŸivuŸutali­ ›­r um aŸipa
 
                                  aŸivuŸåum     1
 10  kuŸippu* aŸivuŸåum^ kàlaiyà­a
 
                                     aŸu     1
 43  påppi­ puŸappàñu* ãr aŸu nàë um
 
                                    a­pi­     2
 60  uëanika© a­pi­ uyarcci m›­a
  1  a­pi­ aim^ tiõai+ kaëavu* e­appañuvatu
 
                                     a­pu     1
 54  a­pu talaippirinta kiëavi t­ŸiŸ
 
                                     a­Ÿu     3
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 47  pulavi+ kàlattu* um puraivatu* a­Ÿu* ›
 41  uriyatu* a­Ÿu* › yàõñu varaiyaŸuttal
 
                                     a­­a     2
 12  a­­a piŸa ~um^ talaippeyal v›ñkai
 30  a­­a marapi­ piŸavum tokaii+
 
                                   a­­avar     1
 26  a­­avar aŸiya+ paõpu* àkum= ›
 
                                     àki     1
 59  eccam àki varum va©i aŸintu
 
                                    àkiyar     1
 12  e­­ai maŸaittal eva­ àkiyar e­a
 
                                     àkum     1
 26  a­­avar aŸiya+ paõpu* àkum= ›
 
                                     àïka     3
 35  àïka àŸu* › avvayi­+ pirivu* ›
Page 4 39  àïka iraõñu* um i©intrkku* uriya
  3  àïka iraõñu* › talaippeyal marapu* ›
 
                                     àïku     1
  8  àïku* uõarntu* allatu ki©avë t›ettu+
 
                                   àïïa­am     2
  5  puõarnta pi­Ÿai ~àïïa­am o©ukàtu
  3  àïïa­am puõarnta ki©av­ ta­-vayi­
 
                                      ày     3
 58  col= › kuŸippu* › ày iraõñu* eccam
 24  ày iraõñu* e­pa varaital àŸu* ›
 28  tantai ta­­aiyar ày iru vãŸŸu* um
 
                                     àyi­     1
 51  kaëavu* uŸai kiëavi t­Ÿuvatu* àyi­
 
                                    àyi­um     2
 29  notumalar varaiyum paruvam àyi­um
 29  ava­ åŸu* a¤cum^ kàlam àyi­um
 
                                     àŸu     5
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 31  àŸu* i­­àmai ~um åŸu* um accam um
 24  ày iraõñu* e­pa varaital àŸu* ›
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
 35  àïka àŸu* › avvayi­+ pirivu* ›
 
                                  àŸupàrttu     1
 30  àŸupàrttu* uŸŸa acca+ kiëavi ~um
 
                                    àŸŸà­     1
 53  pal= àŸŸà­ um va­puŸai kuŸitta­Ÿu
 
                                     à­a     6
 13  ki©avikku* illai talaippeyal à­a
 16  varaiviñai vaitta kàlai à­a
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 25  puraivatu* e­pa kaŸpàl à­a
 55  ava­+ puõarvu* aŸiyum kuŸippi­ à­a
 
                                    ikanta     1
 21  iravu ma­ai ikanta kuŸiyiñattu* allatu
 
                                  ikappi­um     1
 20  pakal+ kuŸi tà­ › ikappi­um varaiyàr
 
                                   ikavàtu     1
 19  iravu+ kuŸi ~› ilvarai ikavàtu
 
                                   iñattà­     1
  4  ev= iñattà­ um^ kaëaviŸku* illai
 
                                    iñattu     1
 29  a+ nàl iñattu* um meynnàõ orãi
 
Page 5                                     iñam     2
 18  aŸiya+ kiëanta iñam e­a mo©ipa
  3  pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
 
                                     iña­     1
 56  iña­ › kàlam eccam meyppàñu
 
                                     iyal     1
 51  nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
 
                                    iyalà­     1
 59  kiëantavaŸŸu* iyalà­ uõarnta­ar koëal ›
 
                                    iyalpu     1
  4  av= iyalpu* allatu kåñña+ kåñal
 
                                   iyaŸkai     1
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 
                                  iyaŸkaiya     1
 52  ka©intu c›ñpañåum iyaŸkaiya e­pa
 
                                   iraõñi­     1
 32  tiïkaë iraõñi­ akam e­a mo©ipa
 
                                    iraõñu     4
 39  àïka iraõñu* um i©intrkku* uriya
 58  col= › kuŸippu* › ày iraõñu* eccam
 24  ày iraõñu* e­pa varaital àŸu* ›
  3  àïka iraõñu* › talaippeyal marapu* ›
 
                                    irantu     2
  6  irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
  5  irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›
 
                                    iravi­     1
 18  kuŸi ~e­appañuvatu* iravi­ um pakali­ um
 
                                   iravi­um     1
 30  iravi­um pakali­um nã varuka* e­Ÿal um
 
                                    iravu     2
 19  iravu+ kuŸi ~› ilvarai ikavàtu
 21  iravu ma­ai ikanta kuŸiyiñattu* allatu
 
                                     iru     1
 28  tantai ta­­aiyar ày iru vãŸŸu* um
 
                                  iru-vayi­     1
  2  kàma+ puõarcci iru-vayi­ ottal
 
                                   iruvarum     1
  7  iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
 
                                      il     1
 48  nàñu* um år um il= um cuññi+
 
Page 6                                     illà     1
 14  màŸukë illà mo©iyumàr uëa ~›
 
                                    illai     8
  4  ev= iñattà­ um^ kaëaviŸku* illai
  8  tà­ kuŸai uŸutal t©ikku* illai
 21  ki©avŸ c›rtal ki©attikku* illai
 28  mu­­am allatu kåŸŸu* avaõ illai
 31  ta­­ai a©ital um ki©avŸku* illai
 33  kaëavi­uë tavircci ki©avŸku* illai
 46  koñumai illai+ ki©avi m›ŸŸu* ›
 13  ki©avikku* illai talaippeyal à­a
 
                                   ilvarai     1
 19  iravu+ kuŸi ~› ilvarai ikavàtu
 
                                  i©intrkku     1
 39  àïka iraõñu* um i©intrkku* uriya
 
                                    i­mai     1
 57  eccam um kë um i­mai ~um uriya
 
                                   i­maiyi­     1
 15  muŸpaña+ puõaràta col= i­maiyi­+
 
                                     i­Ÿu     3
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 44  a+ poruë+ pañuppi­um varainilai i­Ÿu* ›
 
                                   i­­àmai     1
 31  àŸu* i­­àmai ~um åŸu* um accam um
 
                                   ãõñaiyr     1
 60  kaëavu kaŸpu* e­a+ kaõõiya ãõñaiyr
 
                                      ãr     1
 43  påppi­ puŸappàñu* ãr aŸu nàë um
 
                                uñampañuttaŸku     1
  6  mati ~uñampañuttaŸku* um uriya­ e­pa
 
                                   uõari­um     1
  9  mu­­uŸa uõari­um ava­ kuŸai-uŸŸa
 
                                   uõarcci     2
  7  a+ må­Ÿu* e­pa t©ikku* uõarcci
 10  uëëattu* uõarcci teëëitiŸ karantu
 
                                   uõartal     3
  7  mu­­uŸa uõartal kuŸaiyuŸa uõartal
  7  iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
  7  mu­­uŸa uõartal kuŸaiyuŸa uõartal
 
                                   uõarnta     1
 12  kuŸaiyuŸum^ ki©ava­ai uõarnta t©i
 
Page 7                                  uõarnta­ar     1
 59  kiëantavaŸŸu* iyalà­ uõarnta­ar koëal ›
 
                                   uõarntu     1
  8  àïku* uõarntu* allatu ki©avë t›ettu+
 
                                   uõarppu     1
 50  uõarppu vayi­ vàrà åñal t­ŸiŸ
 
                                     uõñu     1
 11  mu­­uŸu puõarcciyi­ arukal um uõñu* ›
 
                                      um    67
  3  pàïka­riŸ kuŸi talaippeytal um
  6  irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
 12  ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
 12  mu­­uŸu puõarcci muŸaimuŸai ceppal um
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
 12  aŸiyàë pŸal um kuŸiyàë kåŸal um
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 18  kuŸi ~e­appañuvatu* iravi­ um pakali­ um
 25  neññiñai ka©intu poruëvayi­ pirital um
 25  poruëvayi­ piriyàtu* oruva©i+ taõattal um
 28  tantai ta­­aiyar ày iru vãŸŸu* um
 30  kàma mikka ka©i pañar kiëavi ~um
 30  kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
 30  àŸupàrttu* uŸŸa acca+ kiëavi ~um
 30  iravi­um pakali­um nã varuka* e­Ÿal um
 30  ki©av­ ta­­ai vàral e­Ÿal um
 30  ta­­uë kaiyàŸu* eytiñu kiëavi ~um
 31  àŸu* i­­àmai ~um åŸu* um accam um
 38  aracar allà ›­aiyrkku* um
 43  påppi­ puŸappàñu* ãr aŸu nàë um
 52  nilam peyarntu* uŸaiyum ellà+ pirivu* um
 52  o©intr aŸiya ~um aŸiyàmai ~um
 31  àŸu* i­­àmai ~um åŸu* um accam um
 22  ampal um alar um^ kaëavu
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 27  tày aŸivuŸutali­ ›­r um aŸipa
 52  o©intr aŸiya ~um aŸiyàmai ~um
 48  nàñu* um år um il= um cuññi+
 39  àïka iraõñu* um i©intrkku* uriya
 57  eccam um kë um i­mai ~um uriya
 11  mu­­uŸu puõarcciyi­ arukal um uõñu* ›
 36  tal um kàval um uyarntrkku* uriya
 29  aŸattoñu niŸŸal t©ikku* um urittu* ›
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 40  kàtal+ parattai ellàrkku* um urittu* ›
 57  eccam um kë um i­mai ~um uriya
 23  veëippañña pi­Ÿai ~um uriya kiëavi
  6  mati ~uñampañuttaŸku* um uriya­ e­pa
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
 55  ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
 48  nàñu* um år um il= um cuññi+
 31  àŸu* i­­àmai ~um åŸu* um accam um
  3  pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
Page 8  4  ev= iñattà­ um^ kaëaviŸku* illai
 22  ampal um alar um^ kaëavu
 36  tal um kàval um uyarntrkku* uriya
 31  ta­­ai a©ital um ki©avŸku* illai
 53  ellà vàyil um ki©av­ pirivayi­
  5  irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›
 45  puka© um koñumai ~um ki©av­ m›­a
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 12  aŸiyàë pŸal um kuŸiyàë kåŸal um
 45  puka© um koñumai ~um ki©av­ m›­a
 57  eccam um kë um i­mai ~um uriya
 48  nàñu* um år um il= um cuññi+
 12  a­­a piŸa ~um^ talaippeyal v›ñkai
  6  irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
 18  kuŸi ~e­appañuvatu* iravi­ um pakali­ um
  6  pati ~um peyar um piŸa ~um vi­àay+
 47  pulavi+ kàlattu* um puraivatu* a­Ÿu* ›
  6  pati ~um peyar um piŸa ~um vi­àay+
 29  a+ nàl iñattu* um meynnàõ orãi
 50  pulattal tà­ › ki©avaŸku* um varaiyàr
 51  tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr
 53  pal= àŸŸà­ um va­puŸai kuŸitta­Ÿu
  6  pati ~um peyar um piŸa ~um vi­àay+
 
                                   uyarcci     1
 60  uëanika© a­pi­ uyarcci m›­a
 
                                 uyarntrkku     1
 36  tal um kàval um uyarntrkku* uriya
 
                                    urittu     6
 16  kaëavi­uë tavircci kàppu miki­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 29  aŸattoñu niŸŸal t©ikku* um urittu* ›
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 40  kàtal+ parattai ellàrkku* um urittu* ›
 
                                    uriya     5
 36  tal um kàval um uyarntrkku* uriya
 39  àïka iraõñu* um i©intrkku* uriya
 57  eccam um kë um i­mai ~um uriya
 12  mu­­uŸu puõarccikku* uriya e­pa
 23  veëippañña pi­Ÿai ~um uriya kiëavi
 
                                   uriyatu     1
 41  uriyatu* a­Ÿu* › yàõñu varaiyaŸuttal
 
                                    uriya­     1
  6  mati ~uñampañuttaŸku* um uriya­ e­pa
 
                                   uriya­a     1
 14  t©ikku* uriya­a kñày t›ettu
 
                                   uraittal     1
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
 
Page 9                                      uë     1
 11  ta­= uë+ kuŸippi­ai arukum^ t©ikku
 
                                     uëa     3
 10  ki©avë t›ettu+ kuŸaiyuŸåum uëa ~›
 14  màŸukë illà mo©iyumàr uëa ~›
 55  ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
 
                                   uëanika©     1
 60  uëanika© a­pi­ uyarcci m›­a
 
                                    uëva©i     1
  7  iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
 
                                   uëëattu     1
 10  uëëattu* uõarcci teëëitiŸ karantu
 
                                     uŸa     1
 12  ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
 
                                    uŸutal     1
  8  tà­ kuŸai uŸutal t©ikku* illai
 
                                     uŸai     1
 51  kaëavu* uŸai kiëavi t­Ÿuvatu* àyi­
 
                                   uŸaital     1
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 
                                   uŸaiyum     2
 52  nilam peyarntu* uŸaiyum ellà+ pirivu* um
 51  nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
 
                                  uŸaivrkku     1
 41  pirivi­ nãññam nilam peyarntu* uŸaivrkku
 
                                     uŸŸa     1
 30  àŸupàrttu* uŸŸa acca+ kiëavi ~um
 
                                    uŸŸu©i     2
 35  v›ntarkku* uŸŸu©i poruñ-piõi parattai ~e­Ÿu
 39  v›ntarkku* uŸŸu©i+ poruñ-piõi+ pirivu* e­Ÿu
 
                                     åñal     1
 50  uõarppu vayi­ vàrà åñal t­ŸiŸ
 
                                      år     1
 48  nàñu* um år um il= um cuññi+
 
                                     åŸu     2
 29  ava­ åŸu* a¤cum^ kàlam àyi­um
 31  àŸu* i­­àmai ~um åŸu* um accam um
 
                                    eccam     4
 58  col= › kuŸippu* › ày iraõñu* eccam
 59  eccam àki varum va©i aŸintu
 57  eccam um kë um i­mai ~um uriya
Page 10 56  iña­ › kàlam eccam meyppàñu
 
                                   eññi­uë     1
  1  antaõar aru-maŸai ma­Ÿal eññi­uë
 
                                 etirkoëëàtu     1
 29  varaivu* etirkoëëàtu tamar avaõ maŸuppi­um
 
                                    eytiñu     1
 30  ta­­uë kaiyàŸu* eytiñu kiëavi ~um
 
                                     ellà     2
 52  nilam peyarntu* uŸaiyum ellà+ pirivu* um
 53  ellà vàyil um ki©av­ pirivayi­
 
                                    ellàm     3
 30  ta­­ai a©inta kiëavi ellàm
 54  va­puŸai kuŸitta vàyil ellàm
 59  muŸpaña+ kiëanta poruë+ pañaikku* ellàm
 
                                   ellàrkku     1
 40  kàtal+ parattai ellàrkku* um urittu* ›
 
                                      ev     1
  4  ev= iñattà­ um^ kaëaviŸku* illai
 
                                     eva­     1
 12  e­­ai maŸaittal eva­ àkiyar e­a
 
                                     e­a     5
 12  e­­ai maŸaittal eva­ àkiyar e­a
 60  kaëavu kaŸpu* e­a+ kaõõiya ãõñaiyr
 18  aŸiya+ kiëanta iñam e­a mo©ipa
 32  tiïkaë iraõñi­ akam e­a mo©ipa
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
 
                                 e­appañuvatu     3
  1  a­pi­ aim^ tiõai+ kaëavu* e­appañuvatu
 18  kuŸi ~e­appañuvatu* iravi­ um pakali­ um
 15  kaŸpu* e­appañuvatu kaëavi­ va©ittu* ›
 
                                     e­pa     8
  6  mati ~uñampañuttaŸku* um uriya­ e­pa
 12  mu­­uŸu puõarccikku* uriya e­pa
 30  varaital v›ñkai+ poruëa e­pa
 52  ka©intu c›ñpañåum iyaŸkaiya e­pa
 38  puraivatu* e­pa riñattà­a
 25  puraivatu* e­pa kaŸpàl à­a
  7  a+ må­Ÿu* e­pa t©ikku* uõarcci
 24  ày iraõñu* e­pa varaital àŸu* ›
 
                                   e­ma­àr     2
  1  kantaruva va©akkam e­ma­àr pulavar
 54  ciŸaippuŸam^ kuŸitta­Ÿu* e­ma­àr pulavar
 
                                    e­Ÿal     2
 30  iravi­um pakali­um nã varuka* e­Ÿal um
Page 11 30  ki©av­ ta­­ai vàral e­Ÿal um
 
                                   e­Ÿàïku     2
 26  tantai tày › ta­­aiyar e­Ÿàïku
 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 
                                     e­Ÿu     5
  3  pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
  7  iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
 24  kaëavu veëippapañña pi­Ÿai varaital e­Ÿu
 35  v›ntarkku* uŸŸu©i poruñ-piõi parattai ~e­Ÿu
 39  v›ntarkku* uŸŸu©i+ poruñ-piõi+ pirivu* e­Ÿu
 
                                    e­­ai     1
 12  e­­ai maŸaittal eva­ àkiyar e­a
 
                                      ›    48
  2  atu ~›
  3  àïka iraõñu* › talaippeyal marapu* ›
  5  irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›
 10  ki©avë t›ettu+ kuŸaiyuŸåum uëa ~›
 11  mu­­uŸu puõarcciyi­ arukal um uõñu* ›
 14  màŸukë illà mo©iyumàr uëa ~›
 15  kaŸpu* e­appañuvatu kaëavi­ va©ittu* ›
 16  kaëavi­uë tavircci kàppu miki­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 24  ày iraõñu* e­pa varaital àŸu* ›
 26  a­­avar aŸiya+ paõpu* àkum= ›
 29  aŸattoñu niŸŸal t©ikku* um urittu* ›
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 35  tal kàval pakai taõi vi­ai ~›
 35  àïka àŸu* › avvayi­+ pirivu* ›
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 40  kàtal+ parattai ellàrkku* um urittu* ›
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 44  a+ poruë+ pañuppi­um varainilai i­Ÿu* ›
 46  koñumai illai+ ki©avi m›ŸŸu* ›
 47  pulavi+ kàlattu* um puraivatu* a­Ÿu* ›
 48  ta­vayi­ kiëappi­ pulavi+ poruññu* ›
 49  ava­ vayi­ kiëappi­ varaivi­ poruññu* ›
 55  ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
 59  kiëantavaŸŸu* iyalà­ uõarnta­ar koëal ›
  2  tà­ › avaë › tamiyar kàõa+
 35  àïka àŸu* › avvayi­+ pirivu* ›
 58  col= › kuŸippu* › ày iraõñu* eccam
 20  pakal+ kuŸi tà­ › ikappi­um varaiyàr
 19  iravu+ kuŸi ~› ilvarai ikavàtu
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 56  iña­ › kàlam eccam meyppàñu
 50  pulattal tà­ › ki©avaŸku* um varaiyàr
 58  col= › kuŸippu* › ày iraõñu* eccam
 56  tiõai ~› kaikë kåŸŸu* › k›ñpr
 56  tiõai ~› kaikë kåŸŸu* › k›ñpr
Page 12 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
  2  tà­ › avaë › tamiyar kàõa+
  3  àïka iraõñu* › talaippeyal marapu* ›
 26  tantai tày › ta­­aiyar e­Ÿàïku
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 41  uriyatu* a­Ÿu* › yàõñu varaiyaŸuttal
 26  veëippañai tà­ › virikkum kàlai+
 
                                  ›­aiyrkku     1
 38  aracar allà ›­aiyrkku* um
 
                                     ›­r     1
 27  tày aŸivuŸutali­ ›­r um aŸipa
 
                                     aim     2
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
  1  a­pi­ aim^ tiõai+ kaëavu* e­appañuvatu
 
                                    ottal     1
  2  kàma+ puõarcci iru-vayi­ ottal
 
                                     orãi     1
 29  a+ nàl iñattu* um meynnàõ orãi
 
                                    oruïku     1
  6  oruïku talaippeyta cevvi nkki+
 
                                   oruva©i     1
 25  poruëvayi­ piriyàtu* oruva©i+ taõattal um
 
                                   o©intr     1
 52  o©intr aŸiya ~um aŸiyàmai ~um
 
                                   o©ukàtu     1
  5  puõarnta pi­Ÿai ~àïïa­am o©ukàtu
 
                                     tal     2
 36  tal um kàval um uyarntrkku* uriya
 35  tal kàval pakai taõi vi­ai ~›
 
                                  riñattà­a     1
 38  puraivatu* e­pa riñattà­a
 
                                     kañi     1
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 
                                   kaõõiya     1
 60  kaëavu kaŸpu* e­a+ kaõõiya ãõñaiyr
 
                                  kantaruva     1
  1  kantaruva va©akkam e­ma­àr pulavar
 
                                   karantu     1
 10  uëëattu* uõarcci teëëitiŸ karantu
 
                                     ka©i     1
Page 13 30  kàma mikka ka©i pañar kiëavi ~um
 
                                   ka©intu     2
 52  ka©intu c›ñpañåum iyaŸkaiya e­pa
 25  neññiñai ka©intu poruëvayi­ pirital um
 
                                  kaëaviŸku     1
  4  ev= iñattà­ um^ kaëaviŸku* illai
 
                                   kaëavi­     1
 15  kaŸpu* e­appañuvatu kaëavi­ va©ittu* ›
 
                                  kaëavi­uë     3
 16  kaëavi­uë tavircci kàppu miki­ urittu* ›
 33  kaëavi­uë tavircci ki©avŸku* illai
 32  kaëavi­uë tavircci varaivi­ nãññam
 
                                    kaëavu     6
 22  ampal um alar um^ kaëavu
 51  kaëavu* uŸai kiëavi t­Ÿuvatu* àyi­
  1  a­pi­ aim^ tiõai+ kaëavu* e­appañuvatu
 60  kaëavu kaŸpu* e­a+ kaõõiya ãõñaiyr
 24  kaëavu veëippañà mu­­uŸa varaital
 24  kaëavu veëippapañña pi­Ÿai varaital e­Ÿu
 
                                    kaŸpàl     1
 25  puraivatu* e­pa kaŸpàl à­a
 
                                   kaŸpi­uë     2
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 44  kaŸpi­uë+ pirint­ parattaiyi­ maŸuttantu
 
                                    kaŸpu     2
 60  kaëavu kaŸpu* e­a+ kaõõiya ãõñaiyr
 15  kaŸpu* e­appañuvatu kaëavi­ va©ittu* ›
 
                                     kàõa     1
  2  tà­ › avaë › tamiyar kàõa+
 
                                    kàtal     1
 40  kàtal+ parattai ellàrkku* um urittu* ›
 
                                    kàppu     3
 29  kàppu+ kaimikku+ kàmam peruki­um
 30  kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
 16  kaëavi­uë tavircci kàppu miki­ urittu* ›
 
                                     kàma     2
  2  kàma+ puõarcci iru-vayi­ ottal
 30  kàma mikka ka©i pañar kiëavi ~um
 
                                    kàmam     1
 29  kàppu+ kaimikku+ kàmam peruki­um
 
                                   kàlattu     1
 47  pulavi+ kàlattu* um puraivatu* a­Ÿu* ›
 
Page 14                                    kàlam     2
 29  ava­ åŸu* a¤cum^ kàlam àyi­um
 56  iña­ › kàlam eccam meyppàñu
 
                                    kàlai     2
 26  veëippañai tà­ › virikkum kàlai+
 16  varaiviñai vaitta kàlai à­a
 
                                  kàlaiyà­a     1
 10  kuŸippu* aŸivuŸåum^ kàlaiyà­a
 
                                    kàval     2
 36  tal um kàval um uyarntrkku* uriya
 35  tal kàval pakai taõi vi­ai ~›
 
                                   ki©atti     1
 47  ki©av­ mu­­ar+ ki©atti taŸ-puka©tal
 
                                  ki©attikku     1
 21  ki©avŸ c›rtal ki©attikku* illai
 
                                  ki©avaŸku     2
 50  pulattal tà­ › ki©avaŸku* um varaiyàr
 51  tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr
 
                                   ki©ava­     1
 25  pañña pi­Ÿai varaiyà+ ki©ava­
 
                                  ki©ava­ai     1
 12  kuŸaiyuŸum^ ki©ava­ai uõarnta t©i
 
                                    ki©avi     2
  6  irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
 46  koñumai illai+ ki©avi m›ŸŸu* ›
 
                                  ki©avikku     1
 13  ki©avikku* illai talaippeyal à­a
 
                                   ki©avë     2
  8  àïku* uõarntu* allatu ki©avë t›ettu+
 10  ki©avë t›ettu+ kuŸaiyuŸåum uëa ~›
 
                                   ki©avŸ     1
 21  ki©avŸ c›rtal ki©attikku* illai
 
                                  ki©avŸku     2
 31  ta­­ai a©ital um ki©avŸku* illai
 33  kaëavi­uë tavircci ki©avŸku* illai
 
                                   ki©av­     7
  3  àïïa­am puõarnta ki©av­ ta­-vayi­
 30  ki©av­ ta­­ai vàral e­Ÿal um
 53  ellà vàyil um ki©av­ pirivayi­
 43  parattaiyi­+ pirinta ki©av­ ma­aivi
 47  ki©av­ mu­­ar+ ki©atti taŸ-puka©tal
  5  irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›
 45  puka© um koñumai ~um ki©av­ m›­a
 
Page 15                                   kiëanta     3
 59  kiëanta alla v›Ÿu piŸa t­Ÿi­um
 18  aŸiya+ kiëanta iñam e­a mo©ipa
 59  muŸpaña+ kiëanta poruë+ pañaikku* ellàm
 
                                 kiëantavaŸŸu     1
 59  kiëantavaŸŸu* iyalà­ uõarnta­ar koëal ›
 
                                   kiëantu     2
  6  putuv­ pla+ poruntupu kiëantu
 12  ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
 
                                   kiëappi­     2
 48  ta­vayi­ kiëappi­ pulavi+ poruññu* ›
 49  ava­ vayi­ kiëappi­ varaivi­ poruññu* ›
 
                                    kiëavi    10
 23  veëippañña pi­Ÿai ~um uriya kiëavi
 30  kàma mikka ka©i pañar kiëavi ~um
 30  kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
 30  àŸupàrttu* uŸŸa acca+ kiëavi ~um
 30  ta­­uë kaiyàŸu* eytiñu kiëavi ~um
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 30  ta­­ai a©inta kiëavi ellàm
  9  pi­­ar allatu kiëavi t­Ÿàtu
 54  a­pu talaippirinta kiëavi t­ŸiŸ
 51  kaëavu* uŸai kiëavi t­Ÿuvatu* àyi­
 
                                     kuŸi     6
 18  kuŸi ~e­appañuvatu* iravi­ um pakali­ um
 19  iravu+ kuŸi ~› ilvarai ikavàtu
  3  pàïka­riŸ kuŸi talaippeytal um
 20  pakal+ kuŸi tà­ › ikappi­um varaiyàr
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 
                                   kuŸitta     1
 54  va­puŸai kuŸitta vàyil ellàm
 
                                  kuŸitta­Ÿu     2
 53  pal= àŸŸà­ um va­puŸai kuŸitta­Ÿu
 54  ciŸaippuŸam^ kuŸitta­Ÿu* e­ma­àr pulavar
 
                                   kuŸippi­     3
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 55  ava­+ puõarvu* aŸiyum kuŸippi­ à­a
 
                                  kuŸippi­ai     1
 11  ta­= uë+ kuŸippi­ai arukum^ t©ikku
 
                                   kuŸippu     3
 10  kuŸippu* aŸivuŸåum^ kàlaiyà­a
 58  col= › kuŸippu* › ày iraõñu* eccam
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 
                                    kuŸiyà     1
Page 16 55  ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
 
                                   kuŸiyàë     1
 12  aŸiyàë pŸal um kuŸiyàë kåŸal um
 
                                 kuŸiyiñattu     1
 21  iravu ma­ai ikanta kuŸiyiñattu* allatu
 
                                    kuŸai     1
  8  tà­ kuŸai uŸutal t©ikku* illai
 
                                  kuŸai-uŸŸa     1
  9  mu­­uŸa uõari­um ava­ kuŸai-uŸŸa
 
                                  kuŸaiyuŸa     1
  7  mu­­uŸa uõartal kuŸaiyuŸa uõartal
 
                                 kuŸaiyuŸàtu     1
  6  irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
 
                                  kuŸaiyuŸu     1
 13  kuŸaiyuŸu puõarcci t©i t›ettu+
 
                                kuŸaiy-uŸutal     1
  5  irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›
 
                                  kuŸaiyuŸum     1
 12  kuŸaiyuŸum^ ki©ava­ai uõarnta t©i
 
                                 kuŸaiyuŸåum     1
 10  ki©avë t›ettu+ kuŸaiyuŸåum uëa ~›
 
                                    kåñal     1
  4  av= iyalpu* allatu kåñña+ kåñal
 
                                    kåñña     1
  4  av= iyalpu* allatu kåñña+ kåñal
 
                                    kåŸal     1
 12  aŸiyàë pŸal um kuŸiyàë kåŸal um
 
                                     kåŸu     1
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
 
                                    kåŸŸu     2
 28  mu­­am allatu kåŸŸu* avaõ illai
 56  tiõai ~› kaikë kåŸŸu* › k›ñpr
 
                                    k›ñpr     1
 56  tiõai ~› kaikë kåŸŸu* › k›ñpr
 
                                    kaikë     1
 56  tiõai ~› kaikë kåŸŸu* › k›ñpr
 
                                   kaimikku     1
 29  kàppu+ kaimikku+ kàmam peruki­um
 
Page 17                                   kaiyaŸu     1
 30  kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
 
                                   kaiyàŸu     1
 30  ta­­uë kaiyàŸu* eytiñu kiëavi ~um
 
                                   koñumai     2
 46  koñumai illai+ ki©avi m›ŸŸu* ›
 45  puka© um koñumai ~um ki©av­ m›­a
 
                                    koëal     2
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 59  kiëantavaŸŸu* iyalà­ uõarnta­ar koëal ›
 
                                    kñày     1
 14  t©ikku* uriya­a kñày t›ettu
 
                                     kë     3
 57  eccam um kë um i­mai ~um uriya
 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 51  tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr
 
                                    ciŸai     2
 12  ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
 30  kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
 
                                 ciŸaippuŸam     2
 54  ciŸaippuŸam^ kuŸitta­Ÿu* e­ma­àr pulavar
 55  ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
 
                                    cuññi     1
 48  nàñu* um år um il= um cuññi+
 
                                    ceppal     1
 12  mu­­uŸu puõarcci muŸaimuŸai ceppal um
 
                                    cevvi     1
  6  oruïku talaippeyta cevvi nkki+
 
                                    ce­Ÿu     1
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
 
                                   c›ñpaña     1
 12  ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
 
                                  c›ñpañåum     1
 52  ka©intu c›ñpañåum iyaŸkaiya e­pa
 
                                    c›rtal     1
 21  ki©avŸ c›rtal ki©attikku* illai
 
                                     col     2
 15  muŸpaña+ puõaràta col= i­maiyi­+
 58  col= › kuŸippu* › ày iraõñu* eccam
 
                                   taõattal     1
 25  poruëvayi­ piriyàtu* oruva©i+ taõattal um
 
Page 18                                     taõi     1
 35  tal kàval pakai taõi vi­ai ~›
 
                                    tantai     2
 28  tantai ta­­aiyar ày iru vãŸŸu* um
 26  tantai tày › ta­­aiyar e­Ÿàïku
 
                                    tamar     1
 29  varaivu* etirkoëëàtu tamar avaõ maŸuppi­um
 
                                   tamiyar     1
  2  tà­ › avaë › tamiyar kàõa+
 
                                   tamiyë     1
  3  pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
 
                                 talaippañal     1
  3  pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
 
                                talaippirinta     1
 54  a­pu talaippirinta kiëavi t­ŸiŸ
 
                                 talaippeyal     3
 13  ki©avikku* illai talaippeyal à­a
  3  àïka iraõñu* › talaippeyal marapu* ›
 12  a­­a piŸa ~um^ talaippeyal v›ñkai
 
                                 talaippeyta     1
  6  oruïku talaippeyta cevvi nkki+
 
                                 talaippeytal     1
  3  pàïka­riŸ kuŸi talaippeytal um
 
                                   tavircci     3
 16  kaëavi­uë tavircci kàppu miki­ urittu* ›
 33  kaëavi­uë tavircci ki©avŸku* illai
 32  kaëavi­uë tavircci varaivi­ nãññam
 
                                 taŸ-puka©tal     1
 47  ki©av­ mu­­ar+ ki©atti taŸ-puka©tal
 
                                     ta­     1
 11  ta­= uë+ kuŸippi­ai arukum^ t©ikku
 
                                   ta­vayi­     1
 48  ta­vayi­ kiëappi­ pulavi+ poruññu* ›
 
                                  ta­-vayi­     1
  3  àïïa­am puõarnta ki©av­ ta­-vayi­
 
                                    ta­­uë     1
 30  ta­­uë kaiyàŸu* eytiñu kiëavi ~um
 
                                    ta­­ai     3
 31  ta­­ai a©ital um ki©avŸku* illai
 30  ta­­ai a©inta kiëavi ellàm
 30  ki©av­ ta­­ai vàral e­Ÿal um
 
Page 19                                  ta­­aiyar     2
 28  tantai ta­­aiyar ày iru vãŸŸu* um
 26  tantai tày › ta­­aiyar e­Ÿàïku
 
                                     tày     2
 27  tày aŸivuŸutali­ ›­r um aŸipa
 26  tantai tày › ta­­aiyar e­Ÿàïku
 
                                     tà­     5
  2  tà­ › avaë › tamiyar kàõa+
 20  pakal+ kuŸi tà­ › ikappi­um varaiyàr
 50  pulattal tà­ › ki©avaŸku* um varaiyàr
 26  veëippañai tà­ › virikkum kàlai+
  8  tà­ kuŸai uŸutal t©ikku* illai
 
                                    tiïkaë     1
 32  tiïkaë iraõñi­ akam e­a mo©ipa
 
                                    tiõai     3
 56  aka­ aim^ tiõai ~um uraittal àŸu* ›
 56  tiõai ~› kaikë kåŸŸu* › k›ñpr
  1  a­pi­ aim^ tiõai+ kaëavu* e­appañuvatu
 
                                 tiõai-nilai     1
 51  tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr
 
                                    tiripu     1
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 
                                    tuŸavu     1
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 
                                   teëëitiŸ     1
 10  uëëattu* uõarcci teëëitiŸ karantu
 
                                    t›ettu     5
  5  paõinta mo©iyàl t©i t›ettu
  8  àïku* uõarntu* allatu ki©avë t›ettu+
 13  kuŸaiyuŸu puõarcci t©i t›ettu+
 14  t©ikku* uriya­a kñày t›ettu
 10  ki©avë t›ettu+ kuŸaiyuŸåum uëa ~›
 
                                    tokaii     1
 30  a­­a marapi­ piŸavum tokaii+
 
                                     t©i     4
 12  kuŸaiyuŸum^ ki©ava­ai uõarnta t©i
  6  irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
  5  paõinta mo©iyàl t©i t›ettu
 13  kuŸaiyuŸu puõarcci t©i t›ettu+
 
                                   t©ikku     5
 11  ta­= uë+ kuŸippi­ai arukum^ t©ikku
  8  tà­ kuŸai uŸutal t©ikku* illai
  7  a+ må­Ÿu* e­pa t©ikku* uõarcci
 29  aŸattoñu niŸŸal t©ikku* um urittu* ›
 14  t©ikku* uriya­a kñày t›ettu
 
Page 20                                    t­Ÿal     1
 55  ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
 
                                   t­Ÿàtu     1
  9  pi­­ar allatu kiëavi t­Ÿàtu
 
                                    t­ŸiŸ     2
 50  uõarppu vayi­ vàrà åñal t­ŸiŸ
 54  a­pu talaippirinta kiëavi t­ŸiŸ
 
                                   t­Ÿi­um     1
 59  kiëanta alla v›Ÿu piŸa t­Ÿi­um
 
                                  t­Ÿuvatu     1
 51  kaëavu* uŸai kiëavi t­Ÿuvatu* àyi­
 
                                    nakàa     1
 12  màya+ puõarcci ava­oñu nakàa
 
                                     nàñu     1
 48  nàñu* um år um il= um cuññi+
 
                                     nàl     1
 29  a+ nàl iñattu* um meynnàõ orãi
 
                                     nàë     1
 43  påppi­ puŸappàñu* ãr aŸu nàë um
 
                                     nila     1
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 
                                    nilam     3
 52  nilam peyarntu* uŸaiyum ellà+ pirivu* um
 51  nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
 41  pirivi­ nãññam nilam peyarntu* uŸaivrkku
 
                                    nilai     1
 51  nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
 
                                   niŸuttal     1
 12  ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
 
                                    niŸŸal     1
 29  aŸattoñu niŸŸal t©ikku* um urittu* ›
 
                                      nã     2
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
 30  iravi­um pakali­um nã varuka* e­Ÿal um
 
                                    nãññam     2
 32  kaëavi­uë tavircci varaivi­ nãññam
 41  pirivi­ nãññam nilam peyarntu* uŸaivrkku
 
                                    nãttu     1
 43  nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›
 
                                   neññiñai     1
Page 21 25  neññiñai ka©intu poruëvayi­ pirital um
 
                                  notumalar     1
 29  notumalar varaiyum paruvam àyi­um
 
                                    nkki     1
  6  oruïku talaippeyta cevvi nkki+
 
                                    pakal     1
 20  pakal+ kuŸi tà­ › ikappi­um varaiyàr
 
                                   pakali­     1
 18  kuŸi ~e­appañuvatu* iravi­ um pakali­ um
 
                                  pakali­um     1
 30  iravi­um pakali­um nã varuka* e­Ÿal um
 
                                    pakai     1
 35  tal kàval pakai taõi vi­ai ~›
 
                                    pañar     1
 30  kàma mikka ka©i pañar kiëavi ~um
 
                                   pañutal     2
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 17  alla kuŸi+ pañutal um avvayi­ urittu* ›
 
                                  pañuppi­um     1
 44  a+ poruë+ pañuppi­um varainilai i­Ÿu* ›
 
                                   pañaikku     1
 59  muŸpaña+ kiëanta poruë+ pañaikku* ellàm
 
                                   pañaittu     1
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 
                                    pañña     1
 25  pañña pi­Ÿai varaiyà+ ki©ava­
 
                                   paõinta     1
  5  paõinta mo©iyàl t©i t›ettu
 
                                    paõpu     1
 26  a­­avar aŸiya+ paõpu* àkum= ›
 
                                     pati     1
  6  pati ~um peyar um piŸa ~um vi­àay+
 
                                    pattu     1
 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 
                                    paya­     1
 56  paya­ › kë e­Ÿàïku* a+ pattu* ›
 
                                   parattai     2
 40  kàtal+ parattai ellàrkku* um urittu* ›
 35  v›ntarkku* uŸŸu©i poruñ-piõi parattai ~e­Ÿu
 
Page 22                                 parattaiyiŸ     1
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 
                                 parattaiyi­     2
 43  parattaiyi­+ pirinta ki©av­ ma­aivi
 44  kaŸpi­uë+ pirint­ parattaiyi­ maŸuttantu
 
                                   paruvam     1
 29  notumalar varaiyum paruvam àyi­um
 
                                     pal     1
 53  pal= àŸŸà­ um va­puŸai kuŸitta­Ÿu
 
                                  pàïka­riŸ     1
  3  pàïka­riŸ kuŸi talaippeytal um
 
                                  pàïk-ila­     1
  3  pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
 
                                  pàrppàrkku     1
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 
                                   pirital     1
 25  neññiñai ka©intu poruëvayi­ pirital um
 
                                   pirinta     1
 43  parattaiyi­+ pirinta ki©av­ ma­aivi
 
                                   pirint­     1
 44  kaŸpi­uë+ pirint­ parattaiyi­ maŸuttantu
 
                                   piriyàtu     1
 25  poruëvayi­ piriyàtu* oruva©i+ taõattal um
 
                                  pirivayi­     1
 53  ellà vàyil um ki©av­ pirivayi­
 
                                   pirivi­     1
 41  pirivi­ nãññam nilam peyarntu* uŸaivrkku
 
                                    pirivu     4
 52  nilam peyarntu* uŸaiyum ellà+ pirivu* um
 39  v›ntarkku* uŸŸu©i+ poruñ-piõi+ pirivu* e­Ÿu
 35  àïka àŸu* › avvayi­+ pirivu* ›
 42  parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›
 
                                     piŸa     3
 12  a­­a piŸa ~um^ talaippeyal v›ñkai
  6  pati ~um peyar um piŸa ~um vi­àay+
 59  kiëanta alla v›Ÿu piŸa t­Ÿi­um
 
                                   piŸavum     1
 30  a­­a marapi­ piŸavum tokaii+
 
                                    pi­Ÿai     4
  5  puõarnta pi­Ÿai ~àïïa­am o©ukàtu
 23  veëippañña pi­Ÿai ~um uriya kiëavi
Page 23 24  kaëavu veëippapañña pi­Ÿai varaital e­Ÿu
 25  pañña pi­Ÿai varaiyà+ ki©ava­
 
                                    pi­­ar     1
  9  pi­­ar allatu kiëavi t­Ÿàtu
 
                                    puka©     1
 45  puka© um koñumai ~um ki©av­ m›­a
 
                                   puõaràta     1
 15  muŸpaña+ puõaràta col= i­maiyi­+
 
                                   puõarcci     4
 12  màya+ puõarcci ava­oñu nakàa
  2  kàma+ puõarcci iru-vayi­ ottal
 13  kuŸaiyuŸu puõarcci t©i t›ettu+
 12  mu­­uŸu puõarcci muŸaimuŸai ceppal um
 
                                 puõarccikku     1
 12  mu­­uŸu puõarccikku* uriya e­pa
 
                                 puõarcciyi­     1
 11  mu­­uŸu puõarcciyi­ arukal um uõñu* ›
 
                                   puõarnta     2
  3  àïïa­am puõarnta ki©av­ ta­-vayi­
  5  puõarnta pi­Ÿai ~àïïa­am o©ukàtu
 
                                   puõarvu     1
 55  ava­+ puõarvu* aŸiyum kuŸippi­ à­a
 
                                   putuv­     1
  6  putuv­ pla+ poruntupu kiëantu
 
                                  puraivatu     3
 47  pulavi+ kàlattu* um puraivatu* a­Ÿu* ›
 38  puraivatu* e­pa riñattà­a
 25  puraivatu* e­pa kaŸpàl à­a
 
                                   pulattal     1
 50  pulattal tà­ › ki©avaŸku* um varaiyàr
 
                                   pulavar     2
  1  kantaruva va©akkam e­ma­àr pulavar
 54  ciŸaippuŸam^ kuŸitta­Ÿu* e­ma­àr pulavar
 
                                    pulavi     2
 47  pulavi+ kàlattu* um puraivatu* a­Ÿu* ›
 48  ta­vayi­ kiëappi­ pulavi+ poruññu* ›
 
                                  puŸappàñu     1
 43  påppi­ puŸappàñu* ãr aŸu nàë um
 
                                    påppi­     1
 43  påppi­ puŸappàñu* ãr aŸu nàë um
 
                                    peyar     2
Page 24  6  pati ~um peyar um piŸa ~um vi­àay+
 51  tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr
 
                                   peyarntu     3
 52  nilam peyarntu* uŸaiyum ellà+ pirivu* um
 51  nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
 41  pirivi­ nãññam nilam peyarntu* uŸaivrkku
 
                                  peruki­um     1
 29  kàppu+ kaimikku+ kàmam peruki­um
 
                                   poruññu     2
 48  ta­vayi­ kiëappi­ pulavi+ poruññu* ›
 49  ava­ vayi­ kiëappi­ varaivi­ poruññu* ›
 
                                  poruñ-piõi     2
 35  v›ntarkku* uŸŸu©i poruñ-piõi parattai ~e­Ÿu
 39  v›ntarkku* uŸŸu©i+ poruñ-piõi+ pirivu* e­Ÿu
 
                                  poruntupu     1
  6  putuv­ pla+ poruntupu kiëantu
 
                                    poruë     2
 44  a+ poruë+ pañuppi­um varainilai i­Ÿu* ›
 59  muŸpaña+ kiëanta poruë+ pañaikku* ellàm
 
                                    poruëa     1
 30  varaital v›ñkai+ poruëa e­pa
 
                                  poruëvayi­     2
 25  neññiñai ka©intu poruëvayi­ pirital um
 25  poruëvayi­ piriyàtu* oruva©i+ taõattal um
 
                                     pla     1
  6  putuv­ pla+ poruntupu kiëantu
 
                                    pŸal     1
 12  aŸiyàë pŸal um kuŸiyàë kåŸal um
 
                                     mati     1
  6  mati ~uñampañuttaŸku* um uriya­ e­pa
 
                                   marapi­     1
 30  a­­a marapi­ piŸavum tokaii+
 
                                    marapu     1
  3  àïka iraõñu* › talaippeyal marapu* ›
 
                                   maruïki­     1
 51  nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
 
                                  maŸuttantu     1
 44  kaŸpi­uë+ pirint­ parattaiyi­ maŸuttantu
 
                                  maŸuppi­um     1
 29  varaivu* etirkoëëàtu tamar avaõ maŸuppi­um
 
Page 25                                  maŸaittal     1
 12  e­­ai maŸaittal eva­ àkiyar e­a
 
                                    ma­ai     1
 21  iravu ma­ai ikanta kuŸiyiñattu* allatu
 
                                   ma­aivi     1
 43  parattaiyi­+ pirinta ki©av­ ma­aivi
 
                                    ma­Ÿal     1
  1  antaõar aru-maŸai ma­Ÿal eññi­uë
 
                                     màya     1
 12  màya+ puõarcci ava­oñu nakàa
 
                                   màŸukë     1
 14  màŸukë illà mo©iyumàr uëa ~›
 
                                    miki­     1
 16  kaëavi­uë tavircci kàppu miki­ urittu* ›
 
                                    mikka     2
 30  kàma mikka ka©i pañar kiëavi ~um
 30  kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
 
                                  muŸaimuŸai     1
 12  mu­­uŸu puõarcci muŸaimuŸai ceppal um
 
                                   muŸpaña     2
 59  muŸpaña+ kiëanta poruë+ pañaikku* ellàm
 15  muŸpaña+ puõaràta col= i­maiyi­+
 
                                    mu­­am     1
 28  mu­­am allatu kåŸŸu* avaõ illai
 
                                    mu­­ar     1
 47  ki©av­ mu­­ar+ ki©atti taŸ-puka©tal
 
                                   mu­­uŸa     3
  9  mu­­uŸa uõari­um ava­ kuŸai-uŸŸa
  7  mu­­uŸa uõartal kuŸaiyuŸa uõartal
 24  kaëavu veëippañà mu­­uŸa varaital
 
                                   mu­­uŸu     3
 12  mu­­uŸu puõarcci muŸaimuŸai ceppal um
 12  mu­­uŸu puõarccikku* uriya e­pa
 11  mu­­uŸu puõarcciyi­ arukal um uõñu* ›
 
                                    må­Ÿu     1
  7  a+ må­Ÿu* e­pa t©ikku* uõarcci
 
                                   meynnàõ     1
 29  a+ nàl iñattu* um meynnàõ orãi
 
                                   meyppàñu     1
 56  iña­ › kàlam eccam meyppàñu
 
Page 26                                    m›ŸŸu     2
  5  irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›
 46  koñumai illai+ ki©avi m›ŸŸu* ›
 
                                     m›­a     2
 45  puka© um koñumai ~um ki©av­ m›­a
 60  uëanika© a­pi­ uyarcci m›­a
 
                                     mo©i     1
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 
                                    mo©ipa     2
 18  aŸiya+ kiëanta iñam e­a mo©ipa
 32  tiïkaë iraõñi­ akam e­a mo©ipa
 
                                   mo©iyàl     1
  5  paõinta mo©iyàl t©i t›ettu
 
                                  mo©iyumàr     1
 14  màŸukë illà mo©iyumàr uëa ~›
 
                                    yàõñu     1
 41  uriyatu* a­Ÿu* › yàõñu varaiyaŸuttal
 
                                    vayi­     2
 49  ava­ vayi­ kiëappi­ varaivi­ poruññu* ›
 50  uõarppu vayi­ vàrà åñal t­ŸiŸ
 
                                    varavu     3
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
 17  ava­ varavu* aŸiyum^ kuŸippi­ à­a
  7  iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
 
                                    varuka     1
 30  iravi­um pakali­um nã varuka* e­Ÿal um
 
                                    varum     1
 59  eccam àki varum va©i aŸintu
 
                                   varaital     4
 24  kaëavu veëippañà mu­­uŸa varaital
 24  ày iraõñu* e­pa varaital àŸu* ›
 24  kaëavu veëippapañña pi­Ÿai varaital e­Ÿu
 30  varaital v›ñkai+ poruëa e­pa
 
                                  varainilai     1
 44  a+ poruë+ pañuppi­um varainilai i­Ÿu* ›
 
                                varaiyaŸuttal     1
 41  uriyatu* a­Ÿu* › yàõñu varaiyaŸuttal
 
                                   varaiyà     1
 25  pañña pi­Ÿai varaiyà+ ki©ava­
 
                                   varaiyàr     3
 20  pakal+ kuŸi tà­ › ikappi­um varaiyàr
 50  pulattal tà­ › ki©avaŸku* um varaiyàr
Page 27 51  tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr
 
                                   varaiyum     1
 29  notumalar varaiyum paruvam àyi­um
 
                                  varaiviñai     1
 16  varaiviñai vaitta kàlai à­a
 
                                   varaivi­     2
 32  kaëavi­uë tavircci varaivi­ nãññam
 49  ava­ vayi­ kiëappi­ varaivi­ poruññu* ›
 
                                   varaivu     2
 34  kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›
 29  varaivu* etirkoëëàtu tamar avaõ maŸuppi­um
 
                                   va©akkam     1
  1  kantaruva va©akkam e­ma­àr pulavar
 
                                     va©i     1
 59  eccam àki varum va©i aŸintu
 
                                   va©ittu     1
 15  kaŸpu* e­appañuvatu kaëavi­ va©ittu* ›
 
                                   va­puŸai     2
 54  va­puŸai kuŸitta vàyil ellàm
 53  pal= àŸŸà­ um va­puŸai kuŸitta­Ÿu
 
                                    vàyil     2
 53  ellà vàyil um ki©av­ pirivayi­
 54  va­puŸai kuŸitta vàyil ellàm
 
                                    vàral     1
 30  ki©av­ ta­­ai vàral e­Ÿal um
 
                                     vàrà     1
 50  uõarppu vayi­ vàrà åñal t­ŸiŸ
 
                                   viñuttal     1
 12  nã ~› ce­Ÿu kåŸu* e­a viñuttal um
 
                                   virikkum     1
 26  veëippañai tà­ › virikkum kàlai+
 
                                    vi­àay     1
  6  pati ~um peyar um piŸa ~um vi­àay+
 
                                    vi­ai     2
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 35  tal kàval pakai taõi vi­ai ~›
 
                                    vãŸŸu     1
 28  tantai ta­­aiyar ày iru vãŸŸu* um
 
                                  veëippañà     1
 24  kaëavu veëippañà mu­­uŸa varaital
 
Page 28                                  veëippañai     1
 26  veëippañai tà­ › virikkum kàlai+
 
                                  veëippañña     1
 23  veëippañña pi­Ÿai ~um uriya kiëavi
 
                                 veëippapañña     1
 24  kaëavu veëippapañña pi­Ÿai varaital e­Ÿu
 
                                    v›ñkai     2
 12  a­­a piŸa ~um^ talaippeyal v›ñkai
 30  varaital v›ñkai+ poruëa e­pa
 
                                  v›ntarkku     2
 35  v›ntarkku* uŸŸu©i poruñ-piõi parattai ~e­Ÿu
 39  v›ntarkku* uŸŸu©i+ poruñ-piõi+ pirivu* e­Ÿu
 
                                    v›ntu     1
 37  v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›
 
                                     v›Ÿu     2
 12  pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
 59  kiëanta alla v›Ÿu piŸa t­Ÿi­um
 
                                    vaitta     1
 16  varaiviñai vaitta kàlai à­a
 
 
 
 
 
1
 TOTAL WORDS READ      =      760
 TOTAL WORDS SELECTED  =      760
 TOTAL WORDS PICKED    =      760
 TOTAL WORDS SAMPLED   =      760
 TOTAL WORDS KEPT      =      760
 TOTAL VOCABULARY      =      406
