((1.kaëavu))
<N 1>

	a­pi­ aim^ tiõai+ kaëavu* e­appañuvatu
	antaõar aru-maŸai ma­Ÿal eññi­uë
	kantaruva va©akkam e­ma­àr pulavar.


<N 2>

	atu ~›
	tà­ › avaë › tamiyar kàõa+
	kàma+ puõarcci iru-vayi­ ottal.


<N 3>

	àïïa­am puõarnta ki©av­ ta­-vayi­
	pàïka­riŸ kuŸi talaippeytal um
	pàïk-ila­ tamiyë iñam^ talaippañal um e­Ÿu
	àïka iraõñu* › talaippeyal marapu* ›.


<N 4>

	av= iyalpu* allatu kåñña+ kåñal
	ev= iñattà­ um^ kaëaviŸku* illai.


<N 5>

	puõarnta pi­Ÿai ~àïïa­am o©ukàtu
	paõinta mo©iyàl t©i t›ettu
	irantu kuŸaiy-uŸutal um^ ki©av­ m›ŸŸu* ›.


<N 6>

	irantu kuŸaiyuŸàtu ki©avi ~um^ t©i ~um
	oruïku talaippeyta cevvi nkki+
	pati ~um peyar um piŸa ~um vi­àay+
	putuv­ pla+ poruntupu kiëantu
	mati ~uñampañuttaŸku* um uriya­ e­pa.


<N 7>

	mu­­uŸa uõartal kuŸaiyuŸa uõartal
	iruvarum uëva©i ava­ varavu* uõartal e­Ÿu
	a+ må­Ÿu* e­pa t©ikku* uõarcci.


<N 8>

	àïku* uõarntu* allatu ki©avë t›ettu+
	tà­ kuŸai uŸutal t©ikku* illai.


<N 9>

	mu­­uŸa uõari­um ava­ kuŸai-uŸŸa
	pi­­ar allatu kiëavi t­Ÿàtu.


<N 10>

	uëëattu* uõarcci teëëitiŸ karantu
	ki©avë t›ettu+ kuŸaiyuŸåum uëa ~›
	kuŸippu* aŸivuŸåum^ kàlaiyà­a.


<N 11>

	ta­= uë+ kuŸippi­ai arukum^ t©ikku
	mu­­uŸu puõarcciyi­ arukal um uõñu* ›.


<N 12>

	kuŸaiyuŸum^ ki©ava­ai uõarnta t©i
	ciŸai ~uŸa+ kiëantu c›ñpaña niŸuttal um
	e­­ai maŸaittal eva­ àkiyar e­a
	mu­­uŸu puõarcci muŸaimuŸai ceppal um
	màya+ puõarcci ava­oñu nakàa
	nã ~› ce­Ÿu kåŸu* e­a viñuttal um
	aŸiyàë pŸal um kuŸiyàë kåŸal um
	pañaittu mo©i kiëavi ~um kuŸippu v›Ÿu koëal um
	a­­a piŸa ~um^ talaippeyal v›ñkai
	mu­­uŸu puõarccikku* uriya e­pa.


<N 13>

	kuŸaiyuŸu puõarcci t©i t›ettu+
	ki©avikku* illai talaippeyal à­a.


<N 14>

	t©ikku* uriya­a kñày t›ettu
	màŸukë illà mo©iyumàr uëa ~›.


<N 15>

	muŸpaña+ puõaràta col= i­maiyi­+
	kaŸpu* e­appañuvatu kaëavi­ va©ittu* ›.


<N 16>

	kaëavi­uë tavircci kàppu miki­ urittu* ›
	varaiviñai vaitta kàlai à­a.


<N 17>

	alla kuŸi+ pañutal um avvayi­ urittu* ›
	ava­ varavu* aŸiyum^ kuŸippi­ à­a.


<N 17>

	alla kuŸi+ pañutal um avvayi­ urittu* ›
	ava­ varavu* aŸiyum^ kuŸippi­ à­a.


<N 18>

	kuŸi ~e­appañuvatu* iravi­ um pakali­ um
	aŸiya+ kiëanta iñam e­a mo©ipa.


<N 19>

	iravu+ kuŸi ~› ilvarai ikavàtu.


<N 20>

	pakal+ kuŸi tà­ › ikappi­um varaiyàr


<N 21>

	iravu ma­ai ikanta kuŸiyiñattu* allatu
	ki©avŸ c›rtal ki©attikku* illai.


<N 22>

	ampal um alar um^ kaëavu.


<N 23>

	veëippañña pi­Ÿai ~um uriya kiëavi.


<N 24>

	kaëavu veëippañà mu­­uŸa varaital
	kaëavu veëippapañña pi­Ÿai varaital e­Ÿu
	ày iraõñu* e­pa varaital àŸu* ›.


<N 25>

	pañña pi­Ÿai varaiyà+ ki©ava­
	neññiñai ka©intu poruëvayi­ pirital um
	poruëvayi­ piriyàtu* oruva©i+ taõattal um
	puraivatu* e­pa kaŸpàl à­a.


<N 26>

	veëippañai tà­ › virikkum kàlai+
	tantai tày › ta­­aiyar e­Ÿàïku
	a­­avar aŸiya+ paõpu* àkum= ›.


<N 27>

	avaruë
	tày aŸivuŸutali­ ›­r um aŸipa.


<N 28>

	tantai ta­­aiyar ày iru vãŸŸu* um
	mu­­am allatu kåŸŸu* avaõ illai.


<N 29>

	kàppu+ kaimikku+ kàmam peruki­um
	notumalar varaiyum paruvam àyi­um
	varaivu* etirkoëëàtu tamar avaõ maŸuppi­um
	ava­ åŸu* a¤cum^ kàlam àyi­um
	a+ nàl iñattu* um meynnàõ orãi
	aŸattoñu niŸŸal t©ikku* um urittu* ›.


<N 30>

	kàma mikka ka©i pañar kiëavi ~um
	kàppu+ ciŸai mikka kaiyaŸu kiëavi ~um
	àŸupàrttu* uŸŸa acca+ kiëavi ~um
	iravi­um pakali­um nã varuka* e­Ÿal um
	ki©av­ ta­­ai vàral e­Ÿal um
	ta­­uë kaiyàŸu* eytiñu kiëavi ~um
	a­­a marapi­ piŸavum tokaii+
	ta­­ai a©inta kiëavi ellàm
	varaital v›ñkai+ poruëa e­pa.


<C SUT>
<N 31>

	àŸu* i­­àmai ~um åŸu* um accam um
	ta­­ai a©ital um ki©avŸku* illai.


<N 32>

	kaëavi­uë tavircci varaivi­ nãññam
	tiïkaë iraõñi­ akam e­a mo©ipa.


<N 33>

	kaëavi­uë tavircci ki©avŸku* illai.





((2. kaŸpu))



<N 34>

	kaŸpi­uë tuŸavu* › kañi varaivu* i­Ÿu* ›.


<N 35>


	tal kàval pakai taõi vi­ai ~›
	v›ntarkku* uŸŸu©i poruñ-piõi parattai ~e­Ÿu
	àïka àŸu* › avvayi­+ pirivu* ›.


<N 36>


	avaŸŸuë,
	tal um kàval um uyarntrkku* uriya.


<N 37>

	v›ntu vi­ai iyaŸkai pàrppàrkku* um urittu* ›.


<N 38>

	aracar allà ›­aiyrkku* um
	puraivatu* e­pa riñattà­a


<N 39>

	v›ntarkku* uŸŸu©i+ poruñ-piõi+ pirivu* e­Ÿu
	àïka iraõñu* um i©intrkku* uriya.


<N 40>

	kàtal+ parattai ellàrkku* um urittu* ›.


<N 41>

	pirivi­ nãññam nilam peyarntu* uŸaivrkku
	uriyatu* a­Ÿu* › yàõñu varaiyaŸuttal.


<N 42>

	parattaiyiŸ pirivu* › nila+ tiripu* i­Ÿu* ›.


<N 43>

	parattaiyi­+ pirinta ki©av­ ma­aivi
	påppi­ puŸappàñu* ãr aŸu nàë um
	nãttu* aka­Ÿu* uŸaital aŸattu* àŸu* a­Ÿu* ›.


<N 44>

	kaŸpi­uë+ pirint­ parattaiyi­ maŸuttantu
	a+ poruë+ pañuppi­um varainilai i­Ÿu* ›.


<N 45>

	puka© um koñumai ~um ki©av­ m›­a.


<N 46>

	koñumai illai+ ki©avi m›ŸŸu* ›.


<N 47>

	ki©av­ mu­­ar+ ki©atti taŸ-puka©tal
	pulavi+ kàlattu* um puraivatu* a­Ÿu* ›.


<N 48>

	nàñu* um år um il= um cuññi+
	ta­vayi­ kiëappi­ pulavi+ poruññu* ›.


<N 49>

	ava­ vayi­ kiëappi­ varaivi­ poruññu* ›.


<N 50>

	uõarppu vayi­ vàrà åñal t­ŸiŸ
	pulattal tà­ › ki©avaŸku* um varaiyàr.


<N 51>

	nilam peyarntu* uŸaiyum nilai ~iyal maruïki­
	kaëavu* uŸai kiëavi t­Ÿuvatu* àyi­
	tiõai-nilai+ peyar+ kë ki©avaŸku* um varaiyàr.


<N 52>

	nilam peyarntu* uŸaiyum ellà+ pirivu* um
	o©intr aŸiya ~um aŸiyàmai ~um
	ka©intu c›ñpañåum iyaŸkaiya e­pa.


<N 53>

	ellà vàyil um ki©av­ pirivayi­
	pal= àŸŸà­ um va­puŸai kuŸitta­Ÿu.


<N 54>

	va­puŸai kuŸitta vàyil ellàm
	a­pu talaippirinta kiëavi t­ŸiŸ
	ciŸaippuŸam^ kuŸitta­Ÿu* e­ma­àr pulavar.


<N 55>

	ciŸaippuŸam kuŸiyà t­Ÿal um uëa ~›
	ava­+ puõarvu* aŸiyum kuŸippi­ à­a.


<N 56>

	tiõai ~› kaikë kåŸŸu* › k›ñpr
	iña­ › kàlam eccam meyppàñu
	paya­ › kë e­Ÿàïku* a+ pattu* ›
	aka­ aim^ tiõai ~um uraittal àŸu* ›.


<N 57>

	avaŸŸuë
	eccam um kë um i­mai ~um uriya.


<N 58>

	col= › kuŸippu* › ày iraõñu* eccam.


<N 59>

	muŸpaña+ kiëanta poruë+ pañaikku* ellàm
	eccam àki varum va©i aŸintu
	kiëanta alla v›Ÿu piŸa t­Ÿi­um
	kiëantavaŸŸu* iyalà­ uõarnta­ar koëal ›.


<N 60>

	kaëavu kaŸpu* e­a+ kaõõiya ãõñaiyr
	uëanika© a­pi­ uyarcci m›­a.
