convers fr_tp.pdy conv4
delz fr_tp.cnv
copy fr_tp.cnv fr_tp.bar
convers fr_tp.bar conv6
delz fr_tp.cnv
copy fr_tp.cnv f_tp.utf
puse
xtr /P245 f_tp.utf
copy f_tp.xxx \az\f_tp245.htm
puse
xtr /P246 f_tp.utf
copy f_tp.xxx \az\f_tp246.htm
xtr /P247 f_tp.utf
copy f_tp.xxx \az\f_tp247.htm
xtr /P248 f_tp.utf
copy f_tp.xxx \az\f_tp248.htm
xtr /P249 f_tp.utf
copy f_tp.xxx \az\f_tp249.htm
xtr /P250 f_tp.utf
copy f_tp.xxx \az\f_tp250.htm
xtr /P251 f_tp.utf
copy f_tp.xxx \az\f_tp251.htm
xtr /P252 f_tp.utf
copy f_tp.xxx \az\f_tp252.htm
xtr /P253 f_tp.utf
copy f_tp.xxx \az\f_tp253.htm
xtr /P254 f_tp.utf
copy f_tp.xxx \az\f_tp254.htm
xtr /P255 f_tp.utf
copy f_tp.xxx \az\f_tp255.htm
xtr /P256 f_tp.utf
copy f_tp.xxx \az\f_tp256.htm
xtr /P257 f_tp.utf
copy f_tp.xxx \az\f_tp257.htm
xtr /P258 f_tp.utf
copy f_tp.xxx \az\f_tp258.htm
xtr /P259 f_tp.utf
copy f_tp.xxx \az\f_tp259.htm
xtr /P260 f_tp.utf
copy f_tp.xxx \az\f_tp260.htm
xtr /P261 f_tp.utf
copy f_tp.xxx \az\f_tp261.htm
xtr /P262 f_tp.utf
copy f_tp.xxx \az\f_tp262.htm
xtr /P263 f_tp.utf
copy f_tp.xxx \az\f_tp263.htm
xtr /P264 f_tp.utf
copy f_tp.xxx \az\f_tp264.htm
xtr /P265 f_tp.utf
copy f_tp.xxx \az\f_tp265.htm
xtr /P266 f_tp.utf
copy f_tp.xxx \az\f_tp266.htm
xtr /P267 f_tp.utf
copy f_tp.xxx \az\f_tp267.htm
xtr /P268 f_tp.utf
copy f_tp.xxx \az\f_tp268.htm
xtr /P269 f_tp.utf
copy f_tp.xxx \az\f_tp269.htm
xtr /P270 f_tp.utf
copy f_tp.xxx \az\f_tp270.htm
xtr /P271 f_tp.utf
copy f_tp.xxx \az\f_tp271.htm

del f_tp.xxx
